import { validateCreativeDirectionInput, validateMochiProjectInput, type CreativeDirectionInput, type MochiProjectInput, type ProductInput } from '@mochi/contracts';
import { ProductionWorkspaceError, ProductionWorkspaceService, type BrowserReferenceMedia, type DeliveryOutputName } from './production-workspace.ts';
import { RuntimeConfiguration } from './runtime-configuration.ts';
import { isPreF1RuntimeStage, isProductionRuntimeDiagnostic, type L3ScriptFinalizationDiagnostic, type L4ProductionCompileDiagnostic, type PreF1RuntimeStage, type ProductionRuntimeDiagnostic } from './production-runtime.ts';
import { decodeProductInput } from './product-input-decoder.ts';

export function createProductionWorkspaceHttpHandler(dependencies:{readonly runtime:RuntimeConfiguration;readonly workspace:ProductionWorkspaceService}):(request:Request)=>Promise<Response> {
  return async request=>{
    const path=new URL(request.url).pathname;
    if(path==='/api/runtime/status'&&request.method==='GET') return Response.json({ok:true,status:dependencies.runtime.status()});
    if(path==='/api/runtime/connect'&&request.method==='POST') return connect(request,dependencies.runtime);
    if(path==='/api/runtime/disconnect'&&request.method==='POST') return Response.json({ok:true,status:dependencies.runtime.disconnect()});
    if(path==='/api/production/foundation'&&request.method==='POST') return foundation(request,dependencies.workspace);
    if(path==='/api/production/blueprint'&&request.method==='POST') return blueprint(request,dependencies.workspace);
    if(path==='/api/production/script'&&request.method==='POST') return script(request,dependencies.workspace);
    if(path==='/api/production/compile'&&request.method==='POST') return compile(request,dependencies.workspace);
    if(path==='/api/production/build'&&request.method==='POST') return build(request,dependencies.workspace);
    if(path==='/api/production/upload'&&request.method==='POST') return upload(request,dependencies.workspace);
    if(path==='/api/production/repair'&&request.method==='POST') return repair(request,dependencies.workspace);
    if(path==='/api/production/sequence'&&request.method==='POST') return sequence(request,dependencies.workspace);
    if(path==='/api/production/final-acceptance'&&request.method==='POST') return finalAcceptance(request,dependencies.workspace);
    if(path==='/api/production/delivery'&&request.method==='GET') return deliveryManifest(request,dependencies.workspace);
    if(path==='/api/production/delivery/receipt'&&request.method==='POST') return deliveryReceipt(request,dependencies.workspace);
    if(path.startsWith('/api/production/delivery/')&&request.method==='GET') return deliveryOutput(request,dependencies.workspace,path.slice('/api/production/delivery/'.length));
    return Response.json({ok:false,error:{code:'NOT_FOUND'}},{status:404});
  };
}
async function connect(request:Request,runtime:RuntimeConfiguration):Promise<Response>{ try { const body=await request.json() as {apiKey?:unknown}; return Response.json({ok:true,status:runtime.connect(body?.apiKey)}); } catch { return failure('INVALID_CONFIGURATION'); } }
async function foundation(request:Request,workspace:ProductionWorkspaceService):Promise<Response>{ try { const form=await request.formData(); const projectId=uniqueField(form,'projectId'),analysisReceiptId=uniqueField(form,'analysisReceiptId'),product=decodeProduct(uniqueValue(form,'product')); if(!projectId||!analysisReceiptId||!product)return failure('INVALID_SETUP'); const references=await decodeProductReferences(form,product); if(!references)return failure('INVALID_SETUP'); return Response.json({ok:true,...await workspace.createFoundation(projectId,product,references,analysisReceiptId)}); } catch(error){return map(error);} }
async function blueprint(request:Request,workspace:ProductionWorkspaceService):Promise<Response>{ try { const body=await exactJson(request,['foundationId','creativeDirection']); if(!body||typeof body.foundationId!=='string'||!isCreativeDirection(body.creativeDirection))return failure('INVALID_SETUP'); return Response.json({ok:true,...await workspace.createBlueprint(body.foundationId,body.creativeDirection)}); } catch(error){return map(error);} }
async function script(request:Request,workspace:ProductionWorkspaceService):Promise<Response>{ try { const body=await exactJson(request,['blueprintId']); if(!body||typeof body.blueprintId!=='string')return failure('INVALID_SETUP'); return Response.json({ok:true,...await workspace.finalizeScript(body.blueprintId)}); } catch(error){return map(error);} }
async function compile(request:Request,workspace:ProductionWorkspaceService):Promise<Response>{ try { const body=await exactJson(request,['scriptId']); if(!body||typeof body.scriptId!=='string')return failure('INVALID_SETUP'); return Response.json({ok:true,...await workspace.compileProduction(body.scriptId)}); } catch(error){return map(error);} }
async function build(request:Request,workspace:ProductionWorkspaceService):Promise<Response>{ try { const form=await request.formData(); const project=decodeProject(form.get('project')); const analysisReceiptId=field(form,'analysisReceiptId'); if(!project) return failure('INVALID_SETUP'); if(!analysisReceiptId) return failure('PRODUCT_ANALYSIS_STALE'); const references=await decodeReferences(form,project); if(!references) return failure('INVALID_SETUP'); const result=await workspace.build(project,references,analysisReceiptId); return Response.json({ok:true,...result}); } catch(error) { return map(error); } }
async function upload(request:Request,workspace:ProductionWorkspaceService):Promise<Response>{ try { const form=await request.formData(); const snapshotId=field(form,'snapshotId'),sceneId=field(form,'sceneId'),candidateAssetId=field(form,'candidateAssetId'),video=form.get('video'); if(!snapshotId||!sceneId||!candidateAssetId||typeof video==='string'||!(video instanceof Blob)) return failure('INVALID_OR_STALE_VIDEO'); const scene=await workspace.uploadAndQc(snapshotId,sceneId,candidateAssetId,{type:video.type,bytes:new Uint8Array(await video.arrayBuffer())}); return Response.json({ok:true,scene}); } catch(error) { return map(error); } }
async function repair(request:Request,workspace:ProductionWorkspaceService):Promise<Response>{ try { const body=await request.json() as {snapshotId?:unknown;sceneId?:unknown;candidateAssetId?:unknown}; if(typeof body?.snapshotId!=='string'||typeof body.sceneId!=='string'||typeof body.candidateAssetId!=='string') return failure('REPAIR_NOT_AVAILABLE'); return Response.json({ok:true,scene:workspace.replaceFailedCandidate(body.snapshotId,body.sceneId,body.candidateAssetId)}); } catch(error) { return map(error); } }
async function sequence(request:Request,workspace:ProductionWorkspaceService):Promise<Response>{ try { const body=await request.json() as {snapshotId?:unknown}; if(typeof body?.snapshotId!=='string') return failure('INVALID_OR_STALE_VIDEO'); return Response.json({ok:true,sequence:await workspace.runSequence(body.snapshotId)}); } catch(error) { return map(error); } }
async function finalAcceptance(request:Request,workspace:ProductionWorkspaceService):Promise<Response>{ try { const body=await request.json() as {snapshotId?:unknown}; if(typeof body?.snapshotId!=='string') return failure('INVALID_OR_STALE_VIDEO'); return Response.json({ok:true,finalAcceptance:workspace.finalAcceptance(body.snapshotId)}); } catch(error) { return map(error); } }
function deliveryManifest(request:Request,workspace:ProductionWorkspaceService):Response { try { const snapshotId=new URL(request.url).searchParams.get('snapshotId'); if(!snapshotId) return failure('DELIVERY_NOT_READY'); return Response.json({ok:true,delivery:workspace.deliveryManifest(snapshotId)}); } catch(error) { return map(error); } }
async function deliveryReceipt(request:Request,workspace:ProductionWorkspaceService):Promise<Response>{ try { const body=await request.json() as {snapshotId?:unknown}; if(typeof body?.snapshotId!=='string') return failure('DELIVERY_NOT_READY'); return Response.json({ok:true,delivery:workspace.recordDelivery(body.snapshotId)}); } catch(error) { return map(error); } }
function deliveryOutput(request:Request,workspace:ProductionWorkspaceService,filename:string):Response { try { const snapshotId=new URL(request.url).searchParams.get('snapshotId'); if(!snapshotId||!isDeliveryOutputName(filename)) return failure('DELIVERY_OUTPUT_NOT_FOUND'); const output=workspace.deliveryOutput(snapshotId,filename); const exact=new Uint8Array(output.bytes.byteLength); exact.set(output.bytes); return new Response(exact.buffer,{headers:{'content-type':output.mimeType,'content-disposition':`attachment; filename="${filename}"`}}); } catch(error) { return map(error); } }
function decodeProject(value:FormDataEntryValue|null):MochiProjectInput|undefined { if(typeof value!=='string') return; try { const project=JSON.parse(value) as MochiProjectInput; return validateMochiProjectInput(project).length===0?project:undefined; } catch { return; } }
function decodeProduct(value:FormDataEntryValue|null|undefined):ProductInput|undefined { if(typeof value!=='string')return; try{return decodeProductInput(JSON.parse(value));}catch{return;} }
async function decodeReferences(form:FormData,project:MochiProjectInput):Promise<readonly BrowserReferenceMedia[]|undefined>{ const result:BrowserReferenceMedia[]=[]; for(const asset of project.product.assets){const value=form.get(`asset:${asset.assetId}`); if(typeof value==='string'||!(value instanceof Blob)||value.type!==asset.mimeType||!value.type.startsWith('image/')||value.size===0)return; result.push({assetId:asset.assetId,mimeType:value.type,dataBase64:Buffer.from(await value.arrayBuffer()).toString('base64')});} return result; }
async function decodeProductReferences(form:FormData,product:ProductInput):Promise<readonly BrowserReferenceMedia[]|undefined>{ const permitted=new Set(['projectId','product','analysisReceiptId',...product.assets.map(asset=>`asset:${asset.assetId}`)]); for(const key of form.keys())if(!permitted.has(key))return; const result:BrowserReferenceMedia[]=[]; for(const asset of product.assets){const values=form.getAll(`asset:${asset.assetId}`);const value=values[0];if(values.length!==1||typeof value==='string'||!(value instanceof Blob)||value.type!==asset.mimeType||!value.type.startsWith('image/')||value.size===0)return;result.push({assetId:asset.assetId,mimeType:value.type,dataBase64:Buffer.from(await value.arrayBuffer()).toString('base64')});}return result; }
async function exactJson(request:Request,keys:readonly string[]):Promise<Record<string,unknown>|undefined>{try{const value=await request.json();if(!value||typeof value!=='object'||Array.isArray(value))return;const record=value as Record<string,unknown>;const actual=Object.keys(record);return actual.length===keys.length&&actual.every(key=>keys.includes(key))?record:undefined;}catch{return;} }
function isCreativeDirection(value:unknown):value is CreativeDirectionInput{if(!value||typeof value!=='object'||Array.isArray(value))return false;const keys=['audience','shootingContext','reviewerPersona','tone','voiceStyle','voiceGender','voiceRegion'],actual=Object.keys(value);return actual.length===keys.length&&actual.every(key=>keys.includes(key))&&validateCreativeDirectionInput(value as CreativeDirectionInput).length===0;}
function field(form:FormData,key:string):string|undefined { const value=form.get(key); return typeof value==='string'&&value.trim().length>0?value:undefined; }
function uniqueValue(form:FormData,key:string):FormDataEntryValue|undefined{const values=form.getAll(key);return values.length===1?values[0]:undefined;}
function uniqueField(form:FormData,key:string):string|undefined{const value=uniqueValue(form,key);return typeof value==='string'&&value.trim().length>0?value:undefined;}
function map(error:unknown):Response { if(error instanceof ProductionWorkspaceError){if(error.code==='PRODUCTION_LAYER_FAILED'&&isLayer(error.layer))return layerFailure(error.layer,error.stage,error.diagnostic);return failure(error.code,error.code==='PRODUCTION_BUILD_FAILED'&&isPreF1RuntimeStage(error.stage)?error.stage:undefined,error.code==='PRODUCTION_BUILD_FAILED'&&isProductionRuntimeDiagnostic(error.diagnostic)?error.diagnostic:undefined);} return failure('PRODUCTION_BUILD_FAILED'); }
function isDeliveryOutputName(value:string):value is DeliveryOutputName { return ['scene-01.mp4','scene-02.mp4','scene-03.mp4','scene-04.mp4','key-points.txt'].includes(value); }
function failure(code:string,stage?:PreF1RuntimeStage,diagnostic?:ProductionRuntimeDiagnostic):Response { return Response.json({ok:false,error:{code,...(stage?{stage}:{}),...(diagnostic?{diagnostic}:{})}},{status:code==='GEMINI_NOT_CONFIGURED'?503:code==='DELIVERY_NOT_READY'||code==='DELIVERY_OUTPUT_NOT_FOUND'?409:400}); }
function isLayer(value:unknown):value is 'L1'|'L2'|'L3'|'L4'{return value==='L1'||value==='L2'||value==='L3'||value==='L4';}
function isL3Diagnostic(value:unknown):value is L3ScriptFinalizationDiagnostic{if(!value||typeof value!=='object'||Array.isArray(value))return false;const item=value as Record<string,unknown>,keys=Object.keys(item);return keys.every(key=>['layer','phase','engineStage'].includes(key))&&item.layer==='L3'&&['INPUT','LOAD','ENGINE','VALIDATE','PERSIST'].includes(String(item.phase))&&(item.engineStage===undefined||item.engineStage==='R4_1_KEY_POINTS'||item.engineStage==='R7_B_DIALOGUE');}
function isL4Diagnostic(value:unknown):value is L4ProductionCompileDiagnostic{if(!value||typeof value!=='object'||Array.isArray(value))return false;const item=value as Record<string,unknown>,keys=Object.keys(item);return keys.every(key=>['layer','phase','engineStage','compileStage'].includes(key))&&item.layer==='L4'&&['INPUT','LOAD','ENGINE','PERSIST','VALIDATE','COMPILE'].includes(String(item.phase))&&(item.engineStage===undefined||item.engineStage==='R8_PRODUCTION_CONTRACT')&&(item.compileStage===undefined||item.compileStage==='SCENE_ANCHOR'||item.compileStage==='FLOW_REQUEST');}
function layerFailure(layer:'L1'|'L2'|'L3'|'L4',stage:unknown,diagnostic:unknown):Response{const safeStage=(layer==='L1'||layer==='L2')&&isPreF1RuntimeStage(stage)?stage:undefined;const safeDiagnostic=layer==='L1'||layer==='L2'?isProductionRuntimeDiagnostic(diagnostic)?diagnostic:undefined:layer==='L3'?isL3Diagnostic(diagnostic)?diagnostic:undefined:isL4Diagnostic(diagnostic)?diagnostic:undefined;return Response.json({ok:false,error:{code:'PRODUCTION_LAYER_FAILED',layer,...(safeStage?{stage:safeStage}:{}),...(safeDiagnostic?{diagnostic:safeDiagnostic}:{})}},{status:400});}
