import { randomUUID } from 'node:crypto';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  GENERATED_SCENE_CANDIDATE_V1, SCHEMA_VERSION, compileSceneAnchorsV1,
  validateMochiProjectInput, type MochiProjectInput, type ProductionSnapshotV1, type SceneAnchorV1
} from '@mochi/contracts';
import {
  compileFlowProductionRequestV1, evaluateSceneQcV1, runManualCandidateSequenceQcV1,
  type FlowProductionRequestV1, type SceneQcReferenceMediaV1, type SceneQcReportV1, type SceneQcVideoMediaV1
} from '@mochi/providers';
import { simpleActionFastTrackPolicyV1 } from '@mochi/core';
import { createProductionRuntime, ProductionRuntimeError } from './production-runtime.ts';
import { createProductionSnapshotStore } from './production-snapshot.ts';
import { RuntimeConfiguration } from './runtime-configuration.ts';

export type ProductionWorkspaceErrorCode = 'GEMINI_NOT_CONFIGURED'|'INVALID_SETUP'|'PRODUCTION_BUILD_FAILED'|'PROMPT_BUDGET_EXCEEDED'|'INVALID_OR_STALE_VIDEO'|'SCENE_QC_FAILED'|'CONTINUITY_QC_FAILED';
export class ProductionWorkspaceError extends Error { constructor(readonly code:ProductionWorkspaceErrorCode) { super(code); this.name='ProductionWorkspaceError'; } }
export interface BrowserReferenceMedia { readonly assetId:string; readonly mimeType:string; readonly dataBase64:string; }
export interface SafeSceneView { readonly sceneId:string; readonly index:1|2|3|4; readonly role:'HOOK'|'FEATURE'|'PROOF'|'CTA'; readonly primaryAction:string; readonly startSummary:string; readonly endSummary:string; readonly keyPoints:readonly [string,string]; readonly dialogue:string; readonly voiceLabel:string; readonly visualRhythm:string; readonly prompt:string; readonly promptCharacterCount:number; readonly promptBudgetStatus:string; readonly lifecycleStatus:'WAITING'|'READY_FOR_FLOW'|'VIDEO_UPLOADED'|'QC_RUNNING'|'QC_PASS'|'QC_FAIL'; readonly referenceAssetIds:readonly string[]; readonly candidateAssetId:string; readonly qcReport?:SafeSceneQcReport; }
export interface SafeSceneQcReport { readonly result:'SCENE_QC_PASS'|'SCENE_QC_FAIL'; readonly frameGates:readonly {readonly gate:string;readonly status:'PASS'|'FAIL'}[]; readonly temporalGates:readonly {readonly gate:string;readonly status:'PASS'|'FAIL'}[]; readonly speechGates:readonly {readonly gate:string;readonly status:'PASS'|'FAIL'}[]; readonly expectedDialogue:string; readonly detectedTranscript:string; readonly exactDialogueMatch:'PASS'|'FAIL'; readonly presentationDynamics:{readonly status:'PASS'|'WARN';readonly notes:string}; }
export interface SafeSequenceView { readonly status:'FOUR_SCENE_SEQUENCE_PASS'|'SEQUENCE_QC_FAILED'; readonly pairs:readonly {readonly fromSceneId:string;readonly toSceneId:string;readonly gates:readonly {readonly gate:string;readonly status:'PASS'|'FAIL'}[]}[]; readonly globalGates:readonly {readonly gate:string;readonly status:'PASS'|'FAIL'}[]; readonly visualVariation:'PASS'|'WARN'; }
type Candidate = { readonly snapshotId:string; readonly sceneId:string; readonly candidateAssetId:string; video?:SceneQcVideoMediaV1; report?:SceneQcReportV1; };
type Active = { readonly snapshot:ProductionSnapshotV1; readonly anchors:readonly [SceneAnchorV1,SceneAnchorV1,SceneAnchorV1,SceneAnchorV1]; readonly requests:readonly [FlowProductionRequestV1,FlowProductionRequestV1,FlowProductionRequestV1,FlowProductionRequestV1]; readonly references:readonly BrowserReferenceMedia[]; readonly candidates:Map<string,Candidate>; sequence?:SafeSequenceView; };
const capabilityMap={REACH:'UNTESTED',PICK_UP:'UNTESTED',HOLD:'UNTESTED',MOVE_CLOSER:'UNTESTED',ROTATE_SLOW:'UNTESTED',PLACE_DOWN:'UNTESTED',OPEN_SIMPLE:'UNTESTED',PRESS_BUTTON:'UNTESTED',POUR_SIMPLE:'UNTESTED',APPLY_SIMPLE:'UNTESTED',POINT:'UNTESTED'} as const;
const stateSummary=(state:unknown)=>JSON.stringify(state).replace(/[{}\"]/g,'').slice(0,180);
const voiceLabel=(identity:string)=>identity==='VN_FEMALE_SOUTH_REVIEW_V1'?'Female — Leda / Leda Custom':'Male — Achird / approved Customize Character state';

export class ProductionWorkspaceService {
  #active:Active|undefined;
  constructor(private readonly runtimeConfiguration:RuntimeConfiguration, private readonly storageRoot=join(tmpdir(),`mochi-v1-browser-${process.pid}`)) {}
  activeSnapshotId():string|undefined { return this.#active?.snapshot.snapshotId; }
  async build(project:MochiProjectInput, references:readonly BrowserReferenceMedia[]):Promise<{readonly snapshotId:string;readonly snapshotStatus:'PERSISTED';readonly scenes:readonly SafeSceneView[]}> {
    const intelligence=this.runtimeConfiguration.provider(); if(!intelligence) throw new ProductionWorkspaceError('GEMINI_NOT_CONFIGURED');
    if(validateMochiProjectInput(project).length || references.length!==project.product.assets.length || references.some((reference,index)=>reference.assetId!==project.product.assets[index]!.assetId||!reference.mimeType.startsWith('image/')||reference.dataBase64.trim().length===0)) throw new ProductionWorkspaceError('INVALID_SETUP');
    let result; try { result=await createProductionRuntime({intelligence,snapshotStore:createProductionSnapshotStore({storageRoot:this.storageRoot})}).run({projectId:project.projectId,product:project.product,creativeDirection:project.creativeDirection,media:references,sourceEvidenceVersion:'BROWSER_RUNTIME_V1',capabilityMap:{...capabilityMap},productionEligibilityPolicy:simpleActionFastTrackPolicyV1}); } catch(error) { if(error instanceof ProductionRuntimeError) throw new ProductionWorkspaceError('PRODUCTION_BUILD_FAILED'); throw new ProductionWorkspaceError('PRODUCTION_BUILD_FAILED'); }
    const anchors=compileSceneAnchorsV1(result.snapshot);
    let requests:readonly FlowProductionRequestV1[]; try { requests=anchors.map(anchor=>compileFlowProductionRequestV1(anchor,anchor.referenceAssetIds.map((logicalAssetId,index)=>({sceneId:anchor.sceneId,logicalAssetId,flowReferenceId:`manual-${index + 1}`})))) as unknown as readonly FlowProductionRequestV1[]; } catch { throw new ProductionWorkspaceError('PROMPT_BUDGET_EXCEEDED'); }
    const typedRequests=requests as unknown as [FlowProductionRequestV1,FlowProductionRequestV1,FlowProductionRequestV1,FlowProductionRequestV1];
    const candidates=new Map<string,Candidate>(); anchors.forEach(anchor=>{const candidateAssetId=`candidate_${randomUUID()}`; candidates.set(anchor.sceneId,{snapshotId:result.snapshot.snapshotId,sceneId:anchor.sceneId,candidateAssetId});});
    this.#active={snapshot:result.snapshot,anchors,requests:typedRequests,references:[...references],candidates};
    return {snapshotId:result.snapshot.snapshotId,snapshotStatus:'PERSISTED',scenes:this.safeScenes()};
  }
  safeScenes():readonly SafeSceneView[] { const active=this.requireActive(); return active.anchors.map((anchor,index)=>this.safeScene(active,anchor,index)) as readonly SafeSceneView[]; }
  async uploadAndQc(snapshotId:string,sceneId:string,candidateAssetId:string,file:{readonly type:string;readonly bytes:Uint8Array}):Promise<SafeSceneView> {
    const active=this.requireActive(); const candidate=active.candidates.get(sceneId); if(snapshotId!==active.snapshot.snapshotId||!candidate||candidate.candidateAssetId!==candidateAssetId||candidate.snapshotId!==snapshotId||!file.type.startsWith('video/')||file.bytes.length===0) throw new ProductionWorkspaceError('INVALID_OR_STALE_VIDEO');
    const index=active.anchors.findIndex(anchor=>anchor.sceneId===sceneId); if(index<0) throw new ProductionWorkspaceError('INVALID_OR_STALE_VIDEO');
    candidate.video={sceneId,candidateAssetId,mimeType:file.type,dataBase64:Buffer.from(file.bytes).toString('base64')};
    const anchor=active.anchors[index]!; const references:SceneQcReferenceMediaV1[]=active.references.map(reference=>({sceneId,assetId:reference.assetId,mimeType:reference.mimeType,dataBase64:reference.dataBase64}));
    try { candidate.report=await evaluateSceneQcV1({candidate:{candidateVersion:GENERATED_SCENE_CANDIDATE_V1,sceneId,candidateAssetId,dialogue:anchor.dialogue,voiceIdentityId:anchor.voiceIdentityId,lifecycleStatus:'QC_PENDING'},anchor,productionRequest:active.requests[index]!,video:candidate.video,references,intelligence:this.runtimeConfiguration.provider()!}); } catch { throw new ProductionWorkspaceError('SCENE_QC_FAILED'); }
    return this.safeScene(active,anchor,index);
  }
  async runSequence(snapshotId:string):Promise<SafeSequenceView> { const active=this.requireActive(); if(snapshotId!==active.snapshot.snapshotId) throw new ProductionWorkspaceError('INVALID_OR_STALE_VIDEO'); const entries=active.anchors.map(anchor=>active.candidates.get(anchor.sceneId)!); if(entries.some(entry=>entry.report?.result!=='SCENE_QC_PASS'||!entry.video)) throw new ProductionWorkspaceError('CONTINUITY_QC_FAILED'); const referenceMedia=active.anchors.map(anchor=>active.references.map(reference=>({sceneId:anchor.sceneId,assetId:reference.assetId,mimeType:reference.mimeType,dataBase64:reference.dataBase64}))) as unknown as [readonly SceneQcReferenceMediaV1[],readonly SceneQcReferenceMediaV1[],readonly SceneQcReferenceMediaV1[],readonly SceneQcReferenceMediaV1[]]; try { const result=await runManualCandidateSequenceQcV1({snapshot:active.snapshot,anchors:active.anchors,referenceMedia,sceneQcReports:entries.map(entry=>entry.report!) as [SceneQcReportV1,SceneQcReportV1,SceneQcReportV1,SceneQcReportV1],videos:entries.map(entry=>entry.video!) as [SceneQcVideoMediaV1,SceneQcVideoMediaV1,SceneQcVideoMediaV1,SceneQcVideoMediaV1],intelligence:this.runtimeConfiguration.provider()!}); const safe:SafeSequenceView={status:result.status==='FOUR_SCENE_SEQUENCE_PASS'?'FOUR_SCENE_SEQUENCE_PASS':'SEQUENCE_QC_FAILED',pairs:result.pairwiseAssessments,globalGates:result.globalGates,visualVariation:result.visualVariation!.status}; active.sequence=safe; return safe; } catch { throw new ProductionWorkspaceError('CONTINUITY_QC_FAILED'); } }
  private requireActive():Active { if(!this.#active) throw new ProductionWorkspaceError('INVALID_SETUP'); return this.#active; }
  private safeScene(active:Active,anchor:SceneAnchorV1,index:number):SafeSceneView { const request=active.requests[index]!; const candidate=active.candidates.get(anchor.sceneId)!; const report=candidate.report; const points=active.snapshot.productionContract.scenes[index]!.keyPoints; const keyPoints:[string,string]=[points[0]!.text,points[1]!.text]; return {sceneId:anchor.sceneId,index:anchor.index,role:anchor.role,primaryAction:anchor.primaryAction,startSummary:stateSummary(anchor.startState),endSummary:stateSummary(anchor.endState),keyPoints,dialogue:anchor.dialogue,voiceLabel:voiceLabel(anchor.voiceIdentityId),visualRhythm:`${anchor.visualRhythm.presentationBeats.join(' · ')}${anchor.visualRhythm.cameraBehavior?` · ${anchor.visualRhythm.cameraBehavior}`:''}`,prompt:request.prompt,promptCharacterCount:request.promptUnicodeCharacterCount,promptBudgetStatus:request.promptBudgetStatus,lifecycleStatus:report?(report.result==='SCENE_QC_PASS'?'QC_PASS':'QC_FAIL'):candidate.video?'VIDEO_UPLOADED':'READY_FOR_FLOW',referenceAssetIds:anchor.referenceAssetIds,candidateAssetId:candidate.candidateAssetId,...(report?{qcReport:this.safeReport(report,anchor.dialogue)}:{})}; }
  private safeReport(report:SceneQcReportV1,expectedDialogue:string):SafeSceneQcReport { return {result:report.result,frameGates:report.frameGates,temporalGates:report.temporalGates,speechGates:report.speechGates,expectedDialogue,detectedTranscript:report.spokenTranscript,exactDialogueMatch:report.speechGates.find(gate=>gate.gate==='EXACT_DIALOGUE_LEXICAL_MATCH')!.status,presentationDynamics:{status:report.presentationDynamics.status,notes:report.presentationDynamics.notes}}; }
}
