import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { App, DeliveryCenter } from './App';
import type { DeliveryManifest, SceneView } from './production-client';

const ids={foundation:`pf_${'1'.repeat(64)}`,blueprint:`sb_${'2'.repeat(64)}`,script:`fs_${'3'.repeat(64)}`,ready:`pr_${'4'.repeat(64)}`,snapshot:`ps_${'5'.repeat(64)}`};
const createObjectUrl=vi.fn((file:File)=>`blob:preview-${file.name}`);const revokeObjectUrl=vi.fn();
beforeEach(()=>{createObjectUrl.mockClear();revokeObjectUrl.mockClear();Object.defineProperty(URL,'createObjectURL',{configurable:true,value:createObjectUrl});Object.defineProperty(URL,'revokeObjectURL',{configurable:true,value:revokeObjectUrl});Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:vi.fn().mockResolvedValue(undefined)}});});
afterEach(()=>{cleanup();vi.restoreAllMocks();});

const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json'}});
const runtimeResponse=(status:'GEMINI_READY'|'GEMINI_NOT_CONFIGURED')=>json({ok:true,status});
function selectImages(names:readonly string[]=['front.jpg']){fireEvent.change(screen.getByLabelText('Add product images'),{target:{files:names.map(name=>new File(['image'],name,{type:'image/jpeg'}))}});}
function enterValidInput(){fireEvent.change(screen.getByLabelText('Product Name'),{target:{value:'Mochi bottle'}});fireEvent.change(screen.getByLabelText('Product Details'),{target:{value:'Factual bottle description'}});fireEvent.change(screen.getByLabelText('Category'),{target:{value:'Beauty'}});selectImages();}
function evidenceResponse():Response{const fetchMock=globalThis.fetch as unknown as ReturnType<typeof vi.fn>;const form=fetchMock.mock.calls.at(-1)?.[1]?.body as FormData;const product=JSON.parse(String(form.get('product'))) as {productId:string;assets:{assetId:string}[]};return json({ok:true,analysisReceiptId:'par_test_receipt_0123456789',receiptVersion:'PRODUCT_ANALYSIS_RECEIPT_V1',evidence:{schemaVersion:'1.0.0',productId:product.productId,canonicalAssetIds:product.assets.map(item=>item.assetId),identityDescription:'A compact white bottle',geometryNotes:['Rounded'],colorNotes:['White'],packagingNotes:['Pump'],labelNotes:['Front label'],claims:[{claimId:'claim-1',text:'Bottle shown',source:'REFERENCE_EVIDENCE',evidenceAssetIds:product.assets.map(item=>item.assetId),allowed:true}],prohibitedInferences:['Do not infer ingredients'],uncertainties:[],contradictions:[]}});}
const roles=['HOOK','FEATURE','PROOF','CTA'] as const;const actions=['PICK_UP','HOLD','ROTATE_SLOW','HOLD'] as const;
const skeletons=()=>roles.map((role,offset)=>({sceneId:`scene-${offset+1}`,index:offset+1,role,primaryAction:actions[offset]!,startSummary:`start ${offset+1}`,endSummary:`end ${offset+1}`,referenceAssetIds:[]}));
const scripts=()=>skeletons().map((scene,offset)=>({...scene,keyPoints:[`point ${offset+1}a`,`point ${offset+1}b`],dialogue:`dialogue ${offset+1}`,voiceLabel:'Female — Leda / Leda Custom'}));
const readyScenes=():SceneView[]=>scripts().map(scene=>({...scene,visualRhythm:'natural hold · subtle handheld',prompt:`safe prompt ${scene.index}`,promptCharacterCount:13,promptBudgetStatus:'TARGET',lifecycleStatus:'READY_FOR_FLOW',candidateAssetId:`candidate_${scene.index}`,attempt:1})) as unknown as SceneView[];
type RouterOptions={l1Fail?:boolean;l3Fail?:boolean;l4Fail?:boolean;deferFoundation?:Promise<Response>;qcPass?:boolean};
function mockLayerApi(options:RouterOptions={}){const fetchMock=vi.fn().mockImplementation((url:unknown)=>{const path=String(url);if(path==='/api/runtime/status')return Promise.resolve(runtimeResponse('GEMINI_READY'));if(path==='/api/product-evidence')return Promise.resolve(evidenceResponse());if(path==='/api/production/foundation'){if(options.deferFoundation)return options.deferFoundation;if(options.l1Fail)return Promise.resolve(json({ok:false,error:{code:'PRODUCTION_LAYER_FAILED',layer:'L1',stage:'R2_A_PRODUCT_TRUTH'}},400));return Promise.resolve(json({ok:true,foundationId:ids.foundation,status:'PASS'}));}if(path==='/api/production/blueprint')return Promise.resolve(json({ok:true,foundationId:ids.foundation,blueprintId:ids.blueprint,status:'PASS',scenes:skeletons()}));if(path==='/api/production/script'){if(options.l3Fail)return Promise.resolve(json({ok:false,error:{code:'PRODUCTION_LAYER_FAILED',layer:'L3',diagnostic:{layer:'L3',phase:'ENGINE',engineStage:'R4_1_KEY_POINTS'}}},400));return Promise.resolve(json({ok:true,blueprintId:ids.blueprint,scriptId:ids.script,status:'PASS',scenes:scripts()}));}if(path==='/api/production/compile'){if(options.l4Fail)return Promise.resolve(json({ok:false,error:{code:'PRODUCTION_LAYER_FAILED',layer:'L4',diagnostic:{layer:'L4',phase:'COMPILE',compileStage:'FLOW_REQUEST'}}},400));return Promise.resolve(json({ok:true,readyId:ids.ready,snapshotId:ids.snapshot,status:'READY_FOR_FLOW',scenes:readyScenes()}));}if(path==='/api/production/upload'&&options.qcPass){const scene={...readyScenes()[0]!,lifecycleStatus:'QC_PASS',qcReport:{result:'SCENE_QC_PASS',frameGates:[{gate:'PRODUCT_FIDELITY',status:'PASS'}],temporalGates:[{gate:'ACTION_COMPLETION',status:'PASS'}],speechGates:[{gate:'EXACT_DIALOGUE_LEXICAL_MATCH',status:'PASS'}],expectedDialogue:'dialogue 1',detectedTranscript:'dialogue 1',exactDialogueMatch:'PASS',presentationDynamics:{status:'PASS',notes:'natural'}}};return Promise.resolve(json({ok:true,scene}));}return Promise.resolve(json({ok:false,error:{code:'NOT_FOUND'}},404));});vi.stubGlobal('fetch',fetchMock);return fetchMock;}
async function setup(){render(<App/>);enterValidInput();await waitFor(()=>expect(screen.getByRole('button',{name:'Analyze Product'})).toBeEnabled());}
async function through(layer:1|2|3|4){fireEvent.click(screen.getByRole('button',{name:'Analyze Product'}));await waitFor(()=>expect(screen.getByRole('button',{name:'✓ Product Foundation Ready'})).toBeInTheDocument());if(layer===1)return;fireEvent.click(screen.getByRole('button',{name:'Build Scene Blueprint'}));await waitFor(()=>expect(screen.getByRole('button',{name:'✓ Blueprint Ready'})).toBeInTheDocument());if(layer===2)return;fireEvent.click(screen.getByRole('button',{name:'Finalize Script'}));await waitFor(()=>expect(screen.getByRole('button',{name:'✓ Script Ready'})).toBeInTheDocument());if(layer===3)return;fireEvent.click(screen.getByRole('button',{name:'Prepare for Flow'}));await waitFor(()=>expect(screen.getByRole('button',{name:'✓ Ready for Flow'})).toBeInTheDocument());}

describe('layered production workflow',()=>{
  it('starts with L2, L3, and L4 locked and removes the old one-click action',async()=>{mockLayerApi();await setup();expect(within(screen.getByRole('article',{name:'L2 Scene Blueprint'})).getByText('LOCKED')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Build Scene Blueprint'})).toBeDisabled();expect(screen.getByRole('button',{name:'Finalize Script'})).toBeDisabled();expect(screen.getByRole('button',{name:'Prepare for Flow'})).toBeDisabled();expect(screen.queryByRole('button',{name:'Create 4-scene plan'})).not.toBeInTheDocument();});
  it('shows Analyze Product RUNNING and PASS and prevents duplicate submission',async()=>{let resolve:(value:Response)=>void=()=>{};const pending=new Promise<Response>(done=>{resolve=done;});const fetchMock=mockLayerApi({deferFoundation:pending});await setup();const button=screen.getByRole('button',{name:'Analyze Product'});fireEvent.click(button);await waitFor(()=>expect(screen.getByRole('button',{name:'Analyzing Product…'})).toBeDisabled());fireEvent.click(screen.getByRole('button',{name:'Analyzing Product…'}));expect(fetchMock.mock.calls.filter(call=>String(call[0])==='/api/product-evidence')).toHaveLength(1);resolve(json({ok:true,foundationId:ids.foundation,status:'PASS'}));await waitFor(()=>expect(screen.getByRole('button',{name:'✓ Product Foundation Ready'})).toBeInTheDocument());});
  it('shows L1 failure and a specific retry without unlocking L2',async()=>{mockLayerApi({l1Fail:true});await setup();fireEvent.click(screen.getByRole('button',{name:'Analyze Product'}));await waitFor(()=>expect(screen.getByRole('button',{name:'Retry Product Foundation'})).toBeInTheDocument());expect(within(screen.getByRole('article',{name:'L1 Product Foundation'})).getByText('FAIL')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Build Scene Blueprint'})).toBeDisabled();});
  it('fresh Analyze Product calls R1 once, then L1 once, and unlocks only L2',async()=>{const fetchMock=mockLayerApi();await setup();await through(1);expect(fetchMock.mock.calls.filter(call=>String(call[0])==='/api/product-evidence')).toHaveLength(1);expect(fetchMock.mock.calls.filter(call=>String(call[0])==='/api/production/foundation')).toHaveLength(1);expect(screen.getByRole('button',{name:'Build Scene Blueprint'})).toBeEnabled();expect(screen.getByRole('button',{name:'Finalize Script'})).toBeDisabled();expect(screen.getByText('PRODUCT FOUNDATION PASS')).toBeInTheDocument();});
  it('L2 renders exactly four skeleton cards with the locked action spine and unlocks L3',async()=>{mockLayerApi();await setup();await through(2);expect(screen.getAllByText(/Scene [1-4] —/)).toHaveLength(4);expect(screen.getAllByText('Script not finalized')).toHaveLength(4);expect(screen.getByText('PICK UP')).toBeInTheDocument();expect(screen.getByText('ROTATE SLOW')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Finalize Script'})).toBeEnabled();});
  it('L3 matures the same four cards with two key points, dialogue, voice, and unlocks L4',async()=>{mockLayerApi();await setup();await through(2);const first=screen.getByText('Scene 1 — HOOK').closest('article');fireEvent.click(screen.getByRole('button',{name:'Finalize Script'}));await waitFor(()=>expect(screen.getByRole('button',{name:'✓ Script Ready'})).toBeInTheDocument());expect(screen.getByText('Scene 1 — HOOK').closest('article')).toBe(first);expect(screen.getByText('point 1a')).toBeInTheDocument();expect(screen.getByText(/dialogue 1/)).toBeInTheDocument();expect(screen.getAllByText('PRODUCTION_COMPILE_PENDING')).toHaveLength(4);expect(screen.getByRole('button',{name:'Prepare for Flow'})).toBeEnabled();});
  it('L4 matures all four cards to READY_FOR_FLOW with prompt controls',async()=>{mockLayerApi();await setup();await through(4);const cards=within(screen.getByRole('region',{name:'Four-scene production'}));expect(cards.getAllByText('READY_FOR_FLOW')).toHaveLength(4);expect(cards.getAllByRole('button',{name:'View Prompt'})).toHaveLength(4);expect(cards.getAllByLabelText(/Upload Generated MP4 Scene/)).toHaveLength(4);});
  it('L3 failure keeps L1/L2 PASS and retries with the same blueprintId',async()=>{const fetchMock=mockLayerApi({l3Fail:true});await setup();await through(2);fireEvent.click(screen.getByRole('button',{name:'Finalize Script'}));await waitFor(()=>expect(screen.getByRole('button',{name:'Retry Script Finalization'})).toBeInTheDocument());expect(within(screen.getByRole('article',{name:'L1 Product Foundation'})).getByText('PASS')).toBeInTheDocument();expect(within(screen.getByRole('article',{name:'L2 Scene Blueprint'})).getByText('PASS')).toBeInTheDocument();expect(screen.getByText(/R4_1_KEY_POINTS/)).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Retry Script Finalization'}));await waitFor(()=>expect(fetchMock.mock.calls.filter(call=>String(call[0])==='/api/production/script')).toHaveLength(2));const bodies=fetchMock.mock.calls.filter(call=>String(call[0])==='/api/production/script').map(call=>JSON.parse(String(call[1]?.body)));expect(bodies).toEqual([{blueprintId:ids.blueprint},{blueprintId:ids.blueprint}]);});
  it('L4 failure keeps L1/L2/L3 PASS and retries with the same scriptId',async()=>{const fetchMock=mockLayerApi({l4Fail:true});await setup();await through(3);fireEvent.click(screen.getByRole('button',{name:'Prepare for Flow'}));await waitFor(()=>expect(screen.getByRole('button',{name:'Retry Production Compile'})).toBeInTheDocument());for(const name of ['L1 Product Foundation','L2 Scene Blueprint','L3 Script Finalization'])expect(within(screen.getByRole('article',{name})).getByText('PASS')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Retry Production Compile'}));await waitFor(()=>expect(fetchMock.mock.calls.filter(call=>String(call[0])==='/api/production/compile')).toHaveLength(2));expect(fetchMock.mock.calls.filter(call=>String(call[0])==='/api/production/compile').map(call=>JSON.parse(String(call[1]?.body)))).toEqual([{scriptId:ids.script},{scriptId:ids.script}]);});
  it('factual and reference mutations visibly invalidate the full lineage',async()=>{mockLayerApi();await setup();await through(4);fireEvent.change(screen.getByLabelText('Product Name'),{target:{value:'Changed bottle'}});await waitFor(()=>expect(within(screen.getByRole('article',{name:'L1 Product Foundation'})).getByText('NEEDS_REANALYSIS')).toBeInTheDocument());for(const name of ['L2 Scene Blueprint','L3 Script Finalization','L4 Production Compile'])expect(within(screen.getByRole('article',{name})).getByText('STALE')).toBeInTheDocument();expect(screen.queryByText('Scene 1 — HOOK')).not.toBeInTheDocument();});
  it('creative mutation preserves L1 and invalidates only L2-L4 without another R1 call',async()=>{const fetchMock=mockLayerApi();await setup();await through(4);fireEvent.change(screen.getByLabelText('Audience'),{target:{value:'GIFT_BUYERS'}});await waitFor(()=>expect(within(screen.getByRole('article',{name:'L2 Scene Blueprint'})).getByText('NEEDS_REBUILD')).toBeInTheDocument());expect(within(screen.getByRole('article',{name:'L1 Product Foundation'})).getByText('PASS')).toBeInTheDocument();expect(within(screen.getByRole('article',{name:'L3 Script Finalization'})).getByText('STALE')).toBeInTheDocument();expect(within(screen.getByRole('article',{name:'L4 Production Compile'})).getByText('STALE')).toBeInTheDocument();expect(fetchMock.mock.calls.filter(call=>String(call[0])==='/api/product-evidence')).toHaveLength(1);});
  it('voice selection changes visible selected state and preserves aria-pressed',async()=>{mockLayerApi();await setup();const female=screen.getByRole('button',{name:'NỮ'}),male=screen.getByRole('button',{name:'NAM'});fireEvent.click(male);expect(male).toHaveAttribute('aria-pressed','true');expect(male).toHaveClass('active');expect(female).toHaveAttribute('aria-pressed','false');});
  it('View Prompt becomes Hide Prompt and Copy Prompt shows Copied feedback',async()=>{mockLayerApi();await setup();await through(4);const view=screen.getAllByRole('button',{name:'View Prompt'})[0]!;fireEvent.click(view);expect(screen.getByRole('button',{name:'Hide Prompt'})).toBeInTheDocument();const copy=screen.getAllByRole('button',{name:'Copy Prompt'})[0]!;fireEvent.click(copy);await waitFor(()=>expect(screen.getAllByRole('button',{name:'Copied'}).length).toBeGreaterThan(0));expect(navigator.clipboard.writeText).toHaveBeenCalledWith('safe prompt 1');});
  it('keeps Product Evidence presentation and reference interaction feedback',async()=>{mockLayerApi();await setup();expect(screen.getByText('1 product reference selected')).toBeInTheDocument();await through(1);expect(screen.getByText('A compact white bottle')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'View analysis details'}));expect(screen.getByText('Prohibited Inferences')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Remove'}));expect(screen.getByText('0 product references selected')).toBeInTheDocument();});
  it('keeps manual upload and Scene QC behavior after L4',async()=>{mockLayerApi({qcPass:true});await setup();await through(4);const upload=screen.getByLabelText('Upload Generated MP4 Scene 1');fireEvent.change(upload,{target:{files:[new File(['video'],'scene.mp4',{type:'video/mp4'})]}});await waitFor(()=>expect(screen.getByText('Scene QC PASS')).toBeInTheDocument());expect(screen.getByText('PRODUCT FIDELITY · PASS')).toBeInTheDocument();});
});

const delivery:DeliveryManifest={version:'DELIVERY_PACKAGE_V1',status:'READY_FOR_DELIVERY',outputs:[{filename:'scene-01.mp4',mimeType:'video/mp4'},{filename:'scene-02.mp4',mimeType:'video/mp4'},{filename:'scene-03.mp4',mimeType:'video/mp4'},{filename:'scene-04.mp4',mimeType:'video/mp4'},{filename:'key-points.txt',mimeType:'text/plain; charset=utf-8'}]};
describe('Delivery preservation',()=>{
  it('appears only when ready and keeps exactly five output names',()=>{render(<DeliveryCenter snapshotId="snapshot-1" delivery={{...delivery,status:'NOT_READY'}} onDelivery={vi.fn()}/>);expect(screen.queryByRole('heading',{name:'Delivery'})).not.toBeInTheDocument();render(<DeliveryCenter snapshotId="snapshot-1" delivery={delivery} onDelivery={vi.fn()}/>);expect(delivery.outputs.map(output=>screen.getByText(output.filename))).toHaveLength(5);});
  it('downloads the exact requested filename',async()=>{const click=vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(new Uint8Array([7,8,9]))));render(<DeliveryCenter snapshotId="snapshot-1" delivery={delivery} onDelivery={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'Download Scene 2'}));await waitFor(()=>expect(globalThis.fetch).toHaveBeenCalledWith('/api/production/delivery/scene-02.mp4?snapshotId=snapshot-1'));expect(click).toHaveBeenCalledOnce();});
  it('writes all five outputs through the folder picker',async()=>{const names:string[]=[];Object.defineProperty(window,'showDirectoryPicker',{configurable:true,value:vi.fn().mockResolvedValue({getFileHandle:async(name:string)=>({createWritable:async()=>({write:async()=>{names.push(name);},close:async()=>{}})})})});vi.stubGlobal('fetch',vi.fn().mockImplementation((url:unknown)=>String(url)==='/api/production/delivery/receipt'?Promise.resolve(json({ok:true,delivery:{...delivery,status:'DELIVERED'}})):Promise.resolve(new Response('bytes'))));const onDelivery=vi.fn();render(<DeliveryCenter snapshotId="snapshot-1" delivery={delivery} onDelivery={onDelivery}/>);fireEvent.click(screen.getByRole('button',{name:'Save 5 files to folder'}));await waitFor(()=>expect(onDelivery).toHaveBeenCalledWith(expect.objectContaining({status:'DELIVERED'})));expect(names).toEqual(delivery.outputs.map(output=>output.filename));});
});
