import type { MochiProjectInput } from '@mochi/contracts';

export type RuntimeStatus='GEMINI_READY'|'GEMINI_NOT_CONFIGURED';
export type SceneLifecycle='WAITING'|'READY_FOR_FLOW'|'VIDEO_UPLOADED'|'QC_RUNNING'|'QC_PASS'|'QC_FAIL';
export interface SceneView { sceneId:string; index:number; role:'HOOK'|'FEATURE'|'PROOF'|'CTA'; primaryAction:string; startSummary:string; endSummary:string; keyPoints:[string,string]; dialogue:string; voiceLabel:string; visualRhythm:string; prompt:string; promptCharacterCount:number; promptBudgetStatus:string; lifecycleStatus:SceneLifecycle; referenceAssetIds:string[]; candidateAssetId:string; qcReport?:{result:string;frameGates:{gate:string;status:string}[];temporalGates:{gate:string;status:string}[];speechGates:{gate:string;status:string}[];expectedDialogue:string;detectedTranscript:string;exactDialogueMatch:string;presentationDynamics:{status:'PASS'|'WARN';notes:string}}; }
export interface SequenceView { status:string;pairs:{fromSceneId:string;toSceneId:string;gates:{gate:string;status:string}[]}[];globalGates:{gate:string;status:string}[];visualVariation:'PASS'|'WARN'; }
export class ProductionClientError extends Error { constructor(readonly code:string){super(code);} }
async function body(response:Response):Promise<any>{ let value:any; try{value=await response.json();}catch{throw new ProductionClientError('INVALID_RESPONSE');} if(!response.ok||value?.ok!==true)throw new ProductionClientError(value?.error?.code??'INVALID_RESPONSE'); return value; }
export async function runtimeStatus():Promise<RuntimeStatus>{return (await body(await fetch('/api/runtime/status'))).status;}
export async function connectGemini(apiKey:string):Promise<RuntimeStatus>{return (await body(await fetch('/api/runtime/connect',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({apiKey})}))).status;}
export async function disconnectGemini():Promise<RuntimeStatus>{return (await body(await fetch('/api/runtime/disconnect',{method:'POST'}))).status;}
export async function buildProduction(project:MochiProjectInput,files:ReadonlyMap<string,File>):Promise<{snapshotId:string;snapshotStatus:string;scenes:SceneView[]}>{const form=new FormData();form.set('project',JSON.stringify(project));for(const asset of project.product.assets){const file=files.get(asset.assetId);if(!file)throw new ProductionClientError('INVALID_SETUP');form.set(`asset:${asset.assetId}`,file);}return body(await fetch('/api/production/build',{method:'POST',body:form}));}
export async function uploadCandidate(snapshotId:string,scene:SceneView,file:File):Promise<SceneView>{const form=new FormData();form.set('snapshotId',snapshotId);form.set('sceneId',scene.sceneId);form.set('candidateAssetId',scene.candidateAssetId);form.set('video',file);return (await body(await fetch('/api/production/upload',{method:'POST',body:form}))).scene;}
export async function runSequence(snapshotId:string):Promise<SequenceView>{return (await body(await fetch('/api/production/sequence',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({snapshotId})}))).sequence;}
