import { isPreF1RuntimeStage, type ActionId, type MochiProjectInput, type PreF1RuntimeStage } from '@mochi/contracts';

export type RuntimeStatus='GEMINI_READY'|'GEMINI_NOT_CONFIGURED';
export type { PreF1RuntimeStage };
export type SceneLifecycle='WAITING'|'READY_FOR_FLOW'|'VIDEO_UPLOADED'|'QC_RUNNING'|'QC_PASS'|'QC_FAIL';
export interface SceneView { sceneId:string; index:number; role:'HOOK'|'FEATURE'|'PROOF'|'CTA'; primaryAction:string; startSummary:string; endSummary:string; keyPoints:[string,string]; dialogue:string; voiceLabel:string; visualRhythm:string; prompt:string; promptCharacterCount:number; promptBudgetStatus:string; lifecycleStatus:SceneLifecycle; referenceAssetIds:string[]; candidateAssetId:string; attempt:number; qcReport?:{result:string;frameGates:{gate:string;status:string}[];temporalGates:{gate:string;status:string}[];speechGates:{gate:string;status:string}[];expectedDialogue:string;detectedTranscript:string;exactDialogueMatch:string;presentationDynamics:{status:'PASS'|'WARN';notes:string}}; }
export interface SequenceView { status:string;pairs:{fromSceneId:string;toSceneId:string;gates:{gate:string;status:string}[]}[];globalGates:{gate:string;status:string}[];visualVariation:'PASS'|'WARN'; }
export interface FinalAcceptanceView { version:'FINAL_ACCEPTANCE_V1'; status:'FINAL_ACCEPTANCE_PASS'|'FINAL_ACCEPTANCE_BLOCKED'; blockerCodes:string[]; }
export type DeliveryOutputName='scene-01.mp4'|'scene-02.mp4'|'scene-03.mp4'|'scene-04.mp4'|'key-points.txt';
export interface DeliveryManifest { version:'DELIVERY_PACKAGE_V1'; status:'NOT_READY'|'READY_FOR_DELIVERY'|'DELIVERED'; outputs:{filename:DeliveryOutputName;mimeType:'video/mp4'|'text/plain; charset=utf-8'}[]; }
export type ProductionDiagnostic = { readonly kind:'R5_STATE_PLANNING'; readonly code:string; readonly sceneIndex:1|2|3|4; readonly primaryAction:ActionId } | { readonly kind:'R6_SCENE_RISK'; readonly sceneIndex:1|2|3|4; readonly primaryAction:ActionId; readonly riskStatus:'CONDITIONAL'|'BLOCKED'; readonly productionEligibility:'EMPIRICAL_SAFE'|'FAST_TRACK_AUTHORIZED'|'BLOCKED'; readonly riskReasons:readonly string[]; readonly replanFailureReason?:string; readonly attempt?:number };
export class ProductionClientError extends Error { constructor(readonly code:string,readonly stage?:PreF1RuntimeStage,readonly diagnostic?:ProductionDiagnostic){super(code);} }
const sceneIndex=(value:unknown):value is 1|2|3|4=>value===1||value===2||value===3||value===4;
const actionIds=new Set<ActionId>(['REACH','PICK_UP','HOLD','MOVE_CLOSER','ROTATE_SLOW','PLACE_DOWN','OPEN_SIMPLE','PRESS_BUTTON','POUR_SIMPLE','APPLY_SIMPLE','POINT']),stateCodes=new Set(['ACTION_EFFECT_MISMATCH','UNSATISFIABLE_INITIAL_STATE','PICK_UP_PRECONDITION','HOLD_PRECONDITION','MOVE_PRECONDITION','ROTATE_PRECONDITION','PLACE_PRECONDITION','INTERACTION_PRECONDITION']),riskReasons=new Set(['action_avoid','action_untested','action_risky','unsupported_secondary_action','product_state_transformation','invalid_pick_up_transition','invalid_hold_transition','invalid_rotate_slow_transition','action_not_simple_fast_track','complexity_3']),replanReasons=new Set(['scene_missing','no_eligible_safer_action','provider_failure','risk_unresolved']);
const actionId=(value:unknown):value is ActionId=>typeof value==='string'&&actionIds.has(value as ActionId);
function diagnostic(value:unknown):ProductionDiagnostic|undefined{if(!value||typeof value!=='object'||Array.isArray(value))return;const d=value as Record<string,unknown>,keys=Object.keys(d);if(d.kind==='R5_STATE_PLANNING'&&keys.length===4&&typeof d.code==='string'&&stateCodes.has(d.code)&&sceneIndex(d.sceneIndex)&&actionId(d.primaryAction))return{kind:d.kind,code:d.code,sceneIndex:d.sceneIndex,primaryAction:d.primaryAction};if(d.kind==='R6_SCENE_RISK'&&keys.every(key=>['kind','sceneIndex','primaryAction','riskStatus','productionEligibility','riskReasons','replanFailureReason','attempt'].includes(key))&&sceneIndex(d.sceneIndex)&&actionId(d.primaryAction)&&(d.riskStatus==='CONDITIONAL'||d.riskStatus==='BLOCKED')&&(d.productionEligibility==='EMPIRICAL_SAFE'||d.productionEligibility==='FAST_TRACK_AUTHORIZED'||d.productionEligibility==='BLOCKED')&&Array.isArray(d.riskReasons)&&d.riskReasons.length<=8&&d.riskReasons.every(item=>typeof item==='string'&&riskReasons.has(item))&&(d.replanFailureReason===undefined||(typeof d.replanFailureReason==='string'&&replanReasons.has(d.replanFailureReason)))&&(d.attempt===undefined||(typeof d.attempt==='number'&&Number.isInteger(d.attempt)&&d.attempt>=0&&d.attempt<=2)))return{kind:d.kind,sceneIndex:d.sceneIndex,primaryAction:d.primaryAction,riskStatus:d.riskStatus,productionEligibility:d.productionEligibility,riskReasons:[...d.riskReasons],...(d.replanFailureReason===undefined?{}:{replanFailureReason:d.replanFailureReason}),...(d.attempt===undefined?{}:{attempt:d.attempt})};}
async function body(response:Response):Promise<any>{ let value:any; try{value=await response.json();}catch{throw new ProductionClientError('INVALID_RESPONSE');} if(!response.ok||value?.ok!==true){const code=value?.error?.code??'INVALID_RESPONSE',stage=code==='PRODUCTION_BUILD_FAILED'&&isPreF1RuntimeStage(value?.error?.stage)?value.error.stage:undefined,safeDiagnostic=code==='PRODUCTION_BUILD_FAILED'?diagnostic(value?.error?.diagnostic):undefined;throw new ProductionClientError(code,stage,safeDiagnostic);} return value; }
export async function runtimeStatus():Promise<RuntimeStatus>{return (await body(await fetch('/api/runtime/status'))).status;}
export async function connectGemini(apiKey:string):Promise<RuntimeStatus>{return (await body(await fetch('/api/runtime/connect',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({apiKey})}))).status;}
export async function disconnectGemini():Promise<RuntimeStatus>{return (await body(await fetch('/api/runtime/disconnect',{method:'POST'}))).status;}
export async function buildProduction(project:MochiProjectInput,files:ReadonlyMap<string,File>,analysisReceiptId:string):Promise<{snapshotId:string;snapshotStatus:string;scenes:SceneView[]}>{if(!analysisReceiptId)throw new ProductionClientError('PRODUCT_ANALYSIS_STALE');const form=new FormData();form.set('project',JSON.stringify(project));form.set('analysisReceiptId',analysisReceiptId);for(const asset of project.product.assets){const file=files.get(asset.assetId);if(!file)throw new ProductionClientError('INVALID_SETUP');form.set(`asset:${asset.assetId}`,file);}return body(await fetch('/api/production/build',{method:'POST',body:form}));}
export async function uploadCandidate(snapshotId:string,scene:SceneView,file:File):Promise<SceneView>{const form=new FormData();form.set('snapshotId',snapshotId);form.set('sceneId',scene.sceneId);form.set('candidateAssetId',scene.candidateAssetId);form.set('video',file);return (await body(await fetch('/api/production/upload',{method:'POST',body:form}))).scene;}
export async function replaceFailedCandidate(snapshotId:string,scene:SceneView):Promise<SceneView>{return (await body(await fetch('/api/production/repair',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({snapshotId,sceneId:scene.sceneId,candidateAssetId:scene.candidateAssetId})}))).scene;}
export async function runSequence(snapshotId:string):Promise<SequenceView>{return (await body(await fetch('/api/production/sequence',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({snapshotId})}))).sequence;}
export async function runFinalAcceptance(snapshotId:string):Promise<FinalAcceptanceView>{return (await body(await fetch('/api/production/final-acceptance',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({snapshotId})}))).finalAcceptance;}
export async function deliveryManifest(snapshotId:string):Promise<DeliveryManifest>{return (await body(await fetch(`/api/production/delivery?snapshotId=${encodeURIComponent(snapshotId)}`))).delivery;}
export async function deliveryOutput(snapshotId:string,filename:DeliveryOutputName):Promise<Blob>{const response=await fetch(`/api/production/delivery/${filename}?snapshotId=${encodeURIComponent(snapshotId)}`);if(!response.ok)throw new ProductionClientError('DELIVERY_NOT_READY');return response.blob();}
export async function recordDelivery(snapshotId:string):Promise<DeliveryManifest>{return (await body(await fetch('/api/production/delivery/receipt',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({snapshotId})}))).delivery;}
