import { isPreF1RuntimeStage, type ActionId, type MochiProjectInput, type PreF1RuntimeStage } from '@mochi/contracts';

export type RuntimeStatus='GEMINI_READY'|'GEMINI_NOT_CONFIGURED';
export type { PreF1RuntimeStage };
export type ProductionLayer='L1'|'L2'|'L3'|'L4';
export type LayerStatus='LOCKED'|'READY'|'RUNNING'|'PASS'|'FAIL'|'STALE'|'NEEDS_REBUILD'|'NEEDS_REANALYSIS'|'READY_FOR_FLOW';
export type SceneLifecycle='WAITING'|'READY_FOR_FLOW'|'VIDEO_UPLOADED'|'QC_RUNNING'|'QC_PASS'|'QC_FAIL';
export interface BlueprintSceneView { sceneId:string;index:1|2|3|4;role:'HOOK'|'FEATURE'|'PROOF'|'CTA';primaryAction:'PICK_UP'|'HOLD'|'ROTATE_SLOW';startSummary:string;endSummary:string;referenceAssetIds:string[]; }
export interface FinalizedScriptSceneView extends BlueprintSceneView { keyPoints:[string,string];dialogue:string;voiceLabel:string; }
export interface SceneView { sceneId:string; index:number; role:'HOOK'|'FEATURE'|'PROOF'|'CTA'; primaryAction:string; startSummary:string; endSummary:string; keyPoints:[string,string]; dialogue:string; voiceLabel:string; visualRhythm:string; prompt:string; promptCharacterCount:number; promptBudgetStatus:string; lifecycleStatus:SceneLifecycle; referenceAssetIds:string[]; candidateAssetId:string; attempt:number; qcReport?:{result:string;frameGates:{gate:string;status:string}[];temporalGates:{gate:string;status:string}[];speechGates:{gate:string;status:string}[];expectedDialogue:string;detectedTranscript:string;exactDialogueMatch:string;presentationDynamics:{status:'PASS'|'WARN';notes:string}}; }
export interface SequenceView { status:string;pairs:{fromSceneId:string;toSceneId:string;gates:{gate:string;status:string}[]}[];globalGates:{gate:string;status:string}[];visualVariation:'PASS'|'WARN'; }
export interface FinalAcceptanceView { version:'FINAL_ACCEPTANCE_V1'; status:'FINAL_ACCEPTANCE_PASS'|'FINAL_ACCEPTANCE_BLOCKED'; blockerCodes:string[]; }
export type DeliveryOutputName='scene-01.mp4'|'scene-02.mp4'|'scene-03.mp4'|'scene-04.mp4'|'key-points.txt';
export interface DeliveryManifest { version:'DELIVERY_PACKAGE_V1'; status:'NOT_READY'|'READY_FOR_DELIVERY'|'DELIVERED'; outputs:{filename:DeliveryOutputName;mimeType:'video/mp4'|'text/plain; charset=utf-8'}[]; }
export type ProductionDiagnostic = { readonly kind:'R2_A_PRODUCT_TRUTH'; readonly productTruthErrorCode:string; readonly providerFailureCode?:string; readonly issueCategories?:readonly string[] } | { readonly kind:'R5_STATE_PLANNING'; readonly code:string; readonly sceneIndex:1|2|3|4; readonly primaryAction:ActionId } | { readonly kind:'R6_SCENE_RISK'; readonly sceneIndex:1|2|3|4; readonly primaryAction:ActionId; readonly riskStatus:'CONDITIONAL'|'BLOCKED'; readonly productionEligibility:'EMPIRICAL_SAFE'|'FAST_TRACK_AUTHORIZED'|'BLOCKED'; readonly riskReasons:readonly string[]; readonly replanFailureReason?:string; readonly attempt?:number };
export type LayerDiagnostic=ProductionDiagnostic|{readonly layer:'L3';readonly phase:'INPUT'|'LOAD'|'ENGINE'|'VALIDATE'|'PERSIST';readonly engineStage?:'R4_1_KEY_POINTS'|'R7_B_DIALOGUE'}|{readonly layer:'L4';readonly phase:'INPUT'|'LOAD'|'ENGINE'|'PERSIST'|'VALIDATE'|'COMPILE';readonly engineStage?:'R8_PRODUCTION_CONTRACT';readonly compileStage?:'SCENE_ANCHOR'|'FLOW_REQUEST'};
export class ProductionClientError extends Error { constructor(readonly code:string,readonly stage?:PreF1RuntimeStage,readonly diagnostic?:LayerDiagnostic,readonly layer?:ProductionLayer){super(code);} }
const sceneIndex=(value:unknown):value is 1|2|3|4=>value===1||value===2||value===3||value===4;
const actionIds=new Set<ActionId>(['REACH','PICK_UP','HOLD','MOVE_CLOSER','ROTATE_SLOW','PLACE_DOWN','OPEN_SIMPLE','PRESS_BUTTON','POUR_SIMPLE','APPLY_SIMPLE','POINT']),stateCodes=new Set(['ACTION_EFFECT_MISMATCH','UNSATISFIABLE_INITIAL_STATE','PICK_UP_PRECONDITION','HOLD_PRECONDITION','MOVE_PRECONDITION','ROTATE_PRECONDITION','PLACE_PRECONDITION','INTERACTION_PRECONDITION']),riskReasons=new Set(['action_avoid','action_untested','action_risky','unsupported_secondary_action','product_state_transformation','invalid_pick_up_transition','invalid_hold_transition','invalid_rotate_slow_transition','action_not_simple_fast_track','complexity_3']),replanReasons=new Set(['scene_missing','no_eligible_safer_action','provider_failure','risk_unresolved']),productTruthErrorCodes=new Set(['INVALID_INPUT','INVALID_EVIDENCE','INVALID_SOURCE_VERSION','INVALID_MODEL_OUTPUT','INSUFFICIENT_TRUTH','PROVIDER_FAILURE']),providerFailureCodes=new Set(['CONFIGURATION','AUTHENTICATION','RATE_LIMIT','INVALID_REQUEST','INVALID_RESPONSE','UNAVAILABLE','UNKNOWN']),productTruthIssueCategories=new Set(['DECISION_SHAPE','UNKNOWN_EXCLUSION','DUPLICATE_EXCLUSION','IDENTITY_EXCLUSION','INVALID_EXCLUSION_REASON','IDENTITY_INSUFFICIENT','COMPILED_TRUTH_INVALID']);
const actionId=(value:unknown):value is ActionId=>typeof value==='string'&&actionIds.has(value as ActionId);
function diagnostic(value:unknown):ProductionDiagnostic|undefined{if(!value||typeof value!=='object'||Array.isArray(value))return;const d=value as Record<string,unknown>,keys=Object.keys(d);if(d.kind==='R2_A_PRODUCT_TRUTH'&&keys.every(key=>['kind','productTruthErrorCode','providerFailureCode','issueCategories'].includes(key))&&typeof d.productTruthErrorCode==='string'&&productTruthErrorCodes.has(d.productTruthErrorCode)&&(d.providerFailureCode===undefined||(typeof d.providerFailureCode==='string'&&providerFailureCodes.has(d.providerFailureCode)))&&(d.issueCategories===undefined||(Array.isArray(d.issueCategories)&&d.issueCategories.length<=productTruthIssueCategories.size&&d.issueCategories.every(item=>typeof item==='string'&&productTruthIssueCategories.has(item))&&new Set(d.issueCategories).size===d.issueCategories.length)))return{kind:d.kind,productTruthErrorCode:d.productTruthErrorCode,...(d.providerFailureCode===undefined?{}:{providerFailureCode:d.providerFailureCode as string}),...(d.issueCategories===undefined?{}:{issueCategories:[...d.issueCategories] as string[]})};if(d.kind==='R5_STATE_PLANNING'&&keys.length===4&&typeof d.code==='string'&&stateCodes.has(d.code)&&sceneIndex(d.sceneIndex)&&actionId(d.primaryAction))return{kind:d.kind,code:d.code,sceneIndex:d.sceneIndex,primaryAction:d.primaryAction};if(d.kind==='R6_SCENE_RISK'&&keys.every(key=>['kind','sceneIndex','primaryAction','riskStatus','productionEligibility','riskReasons','replanFailureReason','attempt'].includes(key))&&sceneIndex(d.sceneIndex)&&actionId(d.primaryAction)&&(d.riskStatus==='CONDITIONAL'||d.riskStatus==='BLOCKED')&&(d.productionEligibility==='EMPIRICAL_SAFE'||d.productionEligibility==='FAST_TRACK_AUTHORIZED'||d.productionEligibility==='BLOCKED')&&Array.isArray(d.riskReasons)&&d.riskReasons.length<=8&&d.riskReasons.every(item=>typeof item==='string'&&riskReasons.has(item))&&(d.replanFailureReason===undefined||(typeof d.replanFailureReason==='string'&&replanReasons.has(d.replanFailureReason)))&&(d.attempt===undefined||(typeof d.attempt==='number'&&Number.isInteger(d.attempt)&&d.attempt>=0&&d.attempt<=2)))return{kind:d.kind,sceneIndex:d.sceneIndex,primaryAction:d.primaryAction,riskStatus:d.riskStatus,productionEligibility:d.productionEligibility,riskReasons:[...d.riskReasons],...(d.replanFailureReason===undefined?{}:{replanFailureReason:d.replanFailureReason}),...(d.attempt===undefined?{}:{attempt:d.attempt})};}
const record=(value:unknown):value is Record<string,unknown>=>!!value&&typeof value==='object'&&!Array.isArray(value);
const exact=(value:Record<string,unknown>,keys:readonly string[])=>Object.keys(value).length===keys.length&&Object.keys(value).every(key=>keys.includes(key));
const id=(value:unknown,prefix:string)=>typeof value==='string'&&new RegExp(`^${prefix}_[0-9a-f]{64}$`).test(value);
const strings=(value:unknown):value is string[]=>Array.isArray(value)&&value.every(item=>typeof item==='string');
const roles=['HOOK','FEATURE','PROOF','CTA'] as const;
function blueprintScene(value:unknown,offset:number):BlueprintSceneView|undefined{if(!record(value)||!exact(value,['sceneId','index','role','primaryAction','startSummary','endSummary','referenceAssetIds'])||typeof value.sceneId!=='string'||value.index!==offset+1||value.role!==roles[offset]||!['PICK_UP','HOLD','ROTATE_SLOW'].includes(String(value.primaryAction))||typeof value.startSummary!=='string'||typeof value.endSummary!=='string'||!strings(value.referenceAssetIds))return;return value as unknown as BlueprintSceneView;}
function scriptScene(value:unknown,offset:number):FinalizedScriptSceneView|undefined{if(!record(value)||!exact(value,['sceneId','index','role','primaryAction','startSummary','endSummary','referenceAssetIds','keyPoints','dialogue','voiceLabel']))return;const base=blueprintScene(Object.fromEntries(Object.entries(value).filter(([key])=>!['keyPoints','dialogue','voiceLabel'].includes(key))),offset);if(!base||!Array.isArray(value.keyPoints)||value.keyPoints.length!==2||!value.keyPoints.every(item=>typeof item==='string')||typeof value.dialogue!=='string'||typeof value.voiceLabel!=='string')return;return{...base,keyPoints:[value.keyPoints[0] as string,value.keyPoints[1] as string],dialogue:value.dialogue,voiceLabel:value.voiceLabel};}
function readyScene(value:unknown,offset:number):SceneView|undefined{if(!record(value)||!exact(value,['sceneId','index','role','primaryAction','startSummary','endSummary','keyPoints','dialogue','voiceLabel','visualRhythm','prompt','promptCharacterCount','promptBudgetStatus','lifecycleStatus','referenceAssetIds','candidateAssetId','attempt']))return;const partial={sceneId:value.sceneId,index:value.index,role:value.role,primaryAction:value.primaryAction,startSummary:value.startSummary,endSummary:value.endSummary,referenceAssetIds:value.referenceAssetIds};const base=blueprintScene(partial,offset);if(!base||!Array.isArray(value.keyPoints)||value.keyPoints.length!==2||!value.keyPoints.every(item=>typeof item==='string')||typeof value.dialogue!=='string'||typeof value.voiceLabel!=='string'||typeof value.visualRhythm!=='string'||typeof value.prompt!=='string'||typeof value.promptCharacterCount!=='number'||!Number.isInteger(value.promptCharacterCount)||value.promptCharacterCount<1||value.promptCharacterCount>3200||typeof value.promptBudgetStatus!=='string'||value.lifecycleStatus!=='READY_FOR_FLOW'||typeof value.candidateAssetId!=='string'||!value.candidateAssetId.startsWith('candidate_')||value.attempt!==1)return;return value as unknown as SceneView;}
function layerDiagnostic(value:unknown,layer:ProductionLayer):LayerDiagnostic|undefined{if(layer==='L1'||layer==='L2')return diagnostic(value);if(!record(value))return;const keys=Object.keys(value);if(layer==='L3'&&keys.every(key=>['layer','phase','engineStage'].includes(key))&&value.layer==='L3'&&['INPUT','LOAD','ENGINE','VALIDATE','PERSIST'].includes(String(value.phase))&&(value.engineStage===undefined||value.engineStage==='R4_1_KEY_POINTS'||value.engineStage==='R7_B_DIALOGUE'))return value as LayerDiagnostic;if(layer==='L4'&&keys.every(key=>['layer','phase','engineStage','compileStage'].includes(key))&&value.layer==='L4'&&['INPUT','LOAD','ENGINE','PERSIST','VALIDATE','COMPILE'].includes(String(value.phase))&&(value.engineStage===undefined||value.engineStage==='R8_PRODUCTION_CONTRACT')&&(value.compileStage===undefined||value.compileStage==='SCENE_ANCHOR'||value.compileStage==='FLOW_REQUEST'))return value as LayerDiagnostic;}
function throwLayerFailure(value:unknown):never{if(!record(value)||!exact(value,['ok','error'])||!record(value.error)||value.ok!==false||value.error.code!=='PRODUCTION_LAYER_FAILED'||!['L1','L2','L3','L4'].includes(String(value.error.layer)))throw new ProductionClientError('INVALID_RESPONSE');const layer=value.error.layer as ProductionLayer;const allowed=['code','layer','stage','diagnostic'];const shape=Object.keys(value.error).every(key=>allowed.includes(key));const stage=(layer==='L1'||layer==='L2')&&isPreF1RuntimeStage(value.error.stage)?value.error.stage:undefined;const safe=layerDiagnostic(value.error.diagnostic,layer);if(!shape||(value.error.stage!==undefined&&stage===undefined)||(value.error.diagnostic!==undefined&&safe===undefined))throw new ProductionClientError('PRODUCTION_LAYER_FAILED',undefined,undefined,layer);throw new ProductionClientError('PRODUCTION_LAYER_FAILED',stage,safe,layer);}
async function strictLayerBody(response:Response):Promise<Record<string,unknown>>{let value:unknown;try{value=await response.json();}catch{throw new ProductionClientError('INVALID_RESPONSE');}if(!response.ok)throwLayerFailure(value);if(!record(value)||value.ok!==true)throw new ProductionClientError('INVALID_RESPONSE');return value;}
async function body(response:Response):Promise<any>{ let value:any; try{value=await response.json();}catch{throw new ProductionClientError('INVALID_RESPONSE');} if(!response.ok||value?.ok!==true){const code=value?.error?.code??'INVALID_RESPONSE',stage=code==='PRODUCTION_BUILD_FAILED'&&isPreF1RuntimeStage(value?.error?.stage)?value.error.stage:undefined,safeDiagnostic=code==='PRODUCTION_BUILD_FAILED'?diagnostic(value?.error?.diagnostic):undefined;throw new ProductionClientError(code,stage,safeDiagnostic);} return value; }
export async function runtimeStatus():Promise<RuntimeStatus>{return (await body(await fetch('/api/runtime/status'))).status;}
export async function connectGemini(apiKey:string):Promise<RuntimeStatus>{return (await body(await fetch('/api/runtime/connect',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({apiKey})}))).status;}
export async function disconnectGemini():Promise<RuntimeStatus>{return (await body(await fetch('/api/runtime/disconnect',{method:'POST'}))).status;}
export async function buildProduction(project:MochiProjectInput,files:ReadonlyMap<string,File>,analysisReceiptId:string):Promise<{snapshotId:string;snapshotStatus:string;scenes:SceneView[]}>{if(!analysisReceiptId)throw new ProductionClientError('PRODUCT_ANALYSIS_STALE');const form=new FormData();form.set('project',JSON.stringify(project));form.set('analysisReceiptId',analysisReceiptId);for(const asset of project.product.assets){const file=files.get(asset.assetId);if(!file)throw new ProductionClientError('INVALID_SETUP');form.set(`asset:${asset.assetId}`,file);}return body(await fetch('/api/production/build',{method:'POST',body:form}));}
export async function createProductFoundation(projectId:string,product:MochiProjectInput['product'],files:ReadonlyMap<string,File>,analysisReceiptId:string):Promise<{foundationId:string;status:'PASS'}>{const form=new FormData();form.set('projectId',projectId);form.set('product',JSON.stringify(product));form.set('analysisReceiptId',analysisReceiptId);for(const asset of product.assets){const file=files.get(asset.assetId);if(!file)throw new ProductionClientError('INVALID_SETUP');form.set(`asset:${asset.assetId}`,file);}const value=await strictLayerBody(await fetch('/api/production/foundation',{method:'POST',body:form}));if(!exact(value,['ok','foundationId','status'])||!id(value.foundationId,'pf')||value.status!=='PASS')throw new ProductionClientError('INVALID_RESPONSE');return{foundationId:value.foundationId as string,status:'PASS'};}
export async function createSceneBlueprint(foundationId:string,creativeDirection:MochiProjectInput['creativeDirection']):Promise<{foundationId:string;blueprintId:string;status:'PASS';scenes:BlueprintSceneView[]}>{const value=await strictLayerBody(await fetch('/api/production/blueprint',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({foundationId,creativeDirection})}));if(!exact(value,['ok','foundationId','blueprintId','status','scenes'])||value.foundationId!==foundationId||!id(value.foundationId,'pf')||!id(value.blueprintId,'sb')||value.status!=='PASS'||!Array.isArray(value.scenes)||value.scenes.length!==4)throw new ProductionClientError('INVALID_RESPONSE');const scenes=value.scenes.map(blueprintScene);if(scenes.some(scene=>!scene))throw new ProductionClientError('INVALID_RESPONSE');return{foundationId,blueprintId:value.blueprintId as string,status:'PASS',scenes:scenes as BlueprintSceneView[]};}
export async function createFinalizedScript(blueprintId:string):Promise<{blueprintId:string;scriptId:string;status:'PASS';scenes:FinalizedScriptSceneView[]}>{const value=await strictLayerBody(await fetch('/api/production/script',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({blueprintId})}));if(!exact(value,['ok','blueprintId','scriptId','status','scenes'])||value.blueprintId!==blueprintId||!id(value.blueprintId,'sb')||!id(value.scriptId,'fs')||value.status!=='PASS'||!Array.isArray(value.scenes)||value.scenes.length!==4)throw new ProductionClientError('INVALID_RESPONSE');const scenes=value.scenes.map(scriptScene);if(scenes.some(scene=>!scene))throw new ProductionClientError('INVALID_RESPONSE');return{blueprintId,scriptId:value.scriptId as string,status:'PASS',scenes:scenes as FinalizedScriptSceneView[]};}
export async function compileProduction(scriptId:string):Promise<{readyId:string;snapshotId:string;status:'READY_FOR_FLOW';scenes:SceneView[]}>{const value=await strictLayerBody(await fetch('/api/production/compile',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({scriptId})}));if(!exact(value,['ok','readyId','snapshotId','status','scenes'])||!id(value.readyId,'pr')||!id(value.snapshotId,'ps')||value.status!=='READY_FOR_FLOW'||!Array.isArray(value.scenes)||value.scenes.length!==4)throw new ProductionClientError('INVALID_RESPONSE');const scenes=value.scenes.map(readyScene);if(scenes.some(scene=>!scene))throw new ProductionClientError('INVALID_RESPONSE');return{readyId:value.readyId as string,snapshotId:value.snapshotId as string,status:'READY_FOR_FLOW',scenes:scenes as SceneView[]};}
export async function uploadCandidate(snapshotId:string,scene:SceneView,file:File):Promise<SceneView>{const form=new FormData();form.set('snapshotId',snapshotId);form.set('sceneId',scene.sceneId);form.set('candidateAssetId',scene.candidateAssetId);form.set('video',file);return (await body(await fetch('/api/production/upload',{method:'POST',body:form}))).scene;}
export async function replaceFailedCandidate(snapshotId:string,scene:SceneView):Promise<SceneView>{return (await body(await fetch('/api/production/repair',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({snapshotId,sceneId:scene.sceneId,candidateAssetId:scene.candidateAssetId})}))).scene;}
export async function runSequence(snapshotId:string):Promise<SequenceView>{return (await body(await fetch('/api/production/sequence',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({snapshotId})}))).sequence;}
export async function runFinalAcceptance(snapshotId:string):Promise<FinalAcceptanceView>{return (await body(await fetch('/api/production/final-acceptance',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({snapshotId})}))).finalAcceptance;}
export async function deliveryManifest(snapshotId:string):Promise<DeliveryManifest>{return (await body(await fetch(`/api/production/delivery?snapshotId=${encodeURIComponent(snapshotId)}`))).delivery;}
export async function deliveryOutput(snapshotId:string,filename:DeliveryOutputName):Promise<Blob>{const response=await fetch(`/api/production/delivery/${filename}?snapshotId=${encodeURIComponent(snapshotId)}`);if(!response.ok)throw new ProductionClientError('DELIVERY_NOT_READY');return response.blob();}
export async function recordDelivery(snapshotId:string):Promise<DeliveryManifest>{return (await body(await fetch('/api/production/delivery/receipt',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({snapshotId})}))).delivery;}
