import { SCHEMA_VERSION, validateCreativeDirectionInput, type CreativeDirectionInput, type GlobalContinuityState, type R2CommittedProductContext } from '@mochi/contracts';
import { IntelligenceProviderError, type IntelligenceProvider } from '@mochi/providers';

export class ContinuityError extends Error { readonly code: 'INVALID_INPUT'|'INVALID_MODEL_OUTPUT'|'PROVIDER_FAILURE'; constructor(code: 'INVALID_INPUT'|'INVALID_MODEL_OUTPUT'|'PROVIDER_FAILURE') { super(`CONTINUITY_ERROR:${code}`); this.code=code; } }
export interface ContinuityDecision { skinTone:string; nailStyle:string; jewelry:string; dominantHand:'LEFT'|'RIGHT'; surface:string; background:string; lighting:string; }
export interface SynthesizeContinuityRequest { context:R2CommittedProductContext; creativeDirection:CreativeDirectionInput; intelligence:IntelligenceProvider; }
const nonBlank=(v:unknown):v is string=>typeof v==='string'&&v.trim().length>0;
export const buildContinuityInstruction=()=> 'CONTINUITY RULES: Return structured JSON only. Propose only hand appearance, dominant hand, surface, background, and lighting. Do not author product facts, claims, source IDs, voice settings, or state.';
export function buildContinuityInputText(r: Pick<SynthesizeContinuityRequest,'context'|'creativeDirection'>) { return `CONTINUITY_INPUT_JSON:\n${JSON.stringify({source:{productId:r.context.productId,sourceEvidenceVersion:r.context.sourceEvidenceVersion,canonicalAssetIds:r.context.canonicalAssetIds},shootingContext:r.creativeDirection.shootingContext})}\nEND_CONTINUITY_INPUT_JSON.`; }
export function validateGlobalContinuityState(s:GlobalContinuityState,c:R2CommittedProductContext,d:CreativeDirectionInput):string[] { const x:string[]=[]; if(s.schemaVersion!==SCHEMA_VERSION)x.push('schema'); if(s.productId!==c.productId||s.sourceEvidenceVersion!==c.sourceEvidenceVersion||JSON.stringify(s.canonicalAssetIds)!==JSON.stringify(c.canonicalAssetIds))x.push('source'); const i=s.immutable; if(!nonBlank(i.handIdentity.skinTone)||!nonBlank(i.handIdentity.nailStyle)||!nonBlank(i.handIdentity.jewelry)||!nonBlank(i.environment.surface)||!nonBlank(i.environment.background)||!nonBlank(i.environment.lighting))x.push('blank'); if(i.handIdentity.dominantHand!=='LEFT'&&i.handIdentity.dominantHand!=='RIGHT')x.push('hand'); if(i.environment.location!==d.shootingContext)x.push('location'); if(i.cameraFamily!=='SMARTPHONE_POV')x.push('camera'); if(i.voiceIdentity.voiceGender!==d.voiceGender||i.voiceIdentity.voiceRegion!==d.voiceRegion||i.voiceIdentity.voiceStyle!==d.voiceStyle)x.push('voice'); return x; }
export async function synthesizeGlobalContinuity(r:SynthesizeContinuityRequest):Promise<GlobalContinuityState> { if(validateCreativeDirectionInput(r.creativeDirection).length)throw new ContinuityError('INVALID_INPUT'); let data:unknown; try { data=(await r.intelligence.analyzeStructured<unknown>({instruction:buildContinuityInstruction(),inputText:buildContinuityInputText(r),media:[],outputSchema:{type:'object',properties:{skinTone:{type:'string'},nailStyle:{type:'string'},jewelry:{type:'string'},dominantHand:{type:'string',enum:['LEFT','RIGHT']},surface:{type:'string'},background:{type:'string'},lighting:{type:'string'}},required:['skinTone','nailStyle','jewelry','dominantHand','surface','background','lighting'],additionalProperties:false},parse:v=>v})).data; } catch(e){if(e instanceof IntelligenceProviderError)throw e; throw new ContinuityError('PROVIDER_FAILURE');} if(!isDecision(data))throw new ContinuityError('INVALID_MODEL_OUTPUT'); const s:GlobalContinuityState={schemaVersion:SCHEMA_VERSION,productId:r.context.productId,sourceEvidenceVersion:r.context.sourceEvidenceVersion,canonicalAssetIds:r.context.canonicalAssetIds,immutable:{handIdentity:{skinTone:data.skinTone,nailStyle:data.nailStyle,jewelry:data.jewelry,dominantHand:data.dominantHand},environment:{location:r.creativeDirection.shootingContext,surface:data.surface,background:data.background,lighting:data.lighting},cameraFamily:'SMARTPHONE_POV',voiceIdentity:{voiceGender:r.creativeDirection.voiceGender,voiceRegion:r.creativeDirection.voiceRegion,voiceStyle:r.creativeDirection.voiceStyle}}}; if(validateGlobalContinuityState(s,r.context,r.creativeDirection).length)throw new ContinuityError('INVALID_MODEL_OUTPUT'); return s; }
function isDecision(v:unknown):v is ContinuityDecision { if(typeof v!=='object'||v===null)return false; const x=v as Record<string,unknown>; return nonBlank(x.skinTone)&&nonBlank(x.nailStyle)&&nonBlank(x.jewelry)&&nonBlank(x.surface)&&nonBlank(x.background)&&nonBlank(x.lighting)&&(x.dominantHand==='LEFT'||x.dominantHand==='RIGHT'); }
