import { HUMAN_REALISM_VERSION, SCHEMA_VERSION, type CreativeDirectionInput, type HumanRealism4ScenePlan, type HumanRealismBehavior, type HumanRealismGlobalConstraints, type R2CommittedProductContext, type StateResolved4ScenePlan, validateHumanRealism4ScenePlan } from '@mochi/contracts';
import { type ActionCapabilityMap } from '@mochi/core';
import { IntelligenceProviderError, type IntelligenceProvider } from '@mochi/providers';
import { validateGlobalContinuityState } from './continuity.ts';
import { buildPlanningTruthCatalog, validatePlan } from './planner.ts';
import { evaluateSceneRisk, type GlobalSceneRiskAssessment } from './risk.ts';
import { resolveSceneStates } from './state.ts';
export class HumanRealismError extends Error { readonly code:'INVALID_INPUT'|'RISK_NOT_READY'|'INVALID_MODEL_OUTPUT'|'PROVIDER_FAILURE'; constructor(code:'INVALID_INPUT'|'RISK_NOT_READY'|'INVALID_MODEL_OUTPUT'|'PROVIDER_FAILURE'){super(`HUMAN_REALISM_ERROR:${code}`);this.code=code;} }
export interface HumanRealismRequest { context:R2CommittedProductContext; plan:import('@mochi/contracts').Global4ScenePlan; statePlan:StateResolved4ScenePlan; risk:GlobalSceneRiskAssessment; creativeDirection:CreativeDirectionInput; capabilityMap:ActionCapabilityMap; intelligence:IntelligenceProvider; }
export const HUMAN_REALISM_GLOBAL_CONSTRAINTS:HumanRealismGlobalConstraints={cameraFamily:'SMARTPHONE_POV',reviewerFaceVisibility:'FORBIDDEN',preserveHandIdentity:true,preserveDominantHand:true,noUncontractedSecondHand:true,onePrimaryPhysicalAction:true,noUncontractedCutOrReset:true,noProductTeleportation:true,noHandProductPenetration:true,noImpossibleGrip:true,maintainContactContinuity:true,noRoboticMotion:true,subtleHandheldCameraOnly:true,actionCompletionPriority:true,exactCanonicalStates:true};
const keys=['approachBehavior','gripAndContactBehavior','actionExecutionBehavior','postActionSettleBehavior','cameraBehavior'] as const;
export const buildHumanRealismInstruction=()=> 'HUMAN REALISM RULES: Return structured JSON only. Describe HOW to execute each contracted action naturally. Do not add objectives, mechanisms, dialogue, hands, faces, cinematic moves, resets, or state changes. Preserve the exact canonical start and end state; use plausible grip/contact, controlled acceleration and settling, and subtle smartphone handheld camera response.';
export function buildHumanRealismInputText(r:Pick<HumanRealismRequest,'plan'|'statePlan'|'creativeDirection'>){return `HUMAN_REALISM_INPUT_JSON:\n${JSON.stringify({continuity:r.plan.continuity.immutable,referenceReadiness:r.plan.referenceReadiness,referenceLimitations:r.plan.referenceLimitations,creative:{reviewerPersona:r.creativeDirection.reviewerPersona,tone:r.creativeDirection.tone},scenes:r.statePlan.scenes.map(s=>({role:s.role,physicalObjective:s.physicalObjective,primaryAction:s.primaryAction,desiredStateEffect:s.desiredStateEffect,startState:s.startState,endState:s.endState}))})}\nEND_HUMAN_REALISM_INPUT_JSON.`;}
export async function planHumanRealism(r:HumanRealismRequest):Promise<HumanRealism4ScenePlan>{const usable=r.context.referenceAssessment.assetAssessments.filter(x=>(x.targetVisibility==='CLEAR'||x.targetVisibility==='PARTIAL')&&(x.identityConfidence==='HIGH'||x.identityConfidence==='MEDIUM')).map(x=>x.assetId);if(validateGlobalContinuityState(r.plan.continuity,r.context,r.creativeDirection).length||validatePlan(r.plan,r.context,r.plan.continuity,buildPlanningTruthCatalog(r.context).map(x=>x.id),usable).length)throw new HumanRealismError('INVALID_INPUT');let canonical:StateResolved4ScenePlan;try{canonical=resolveSceneStates(r.plan);}catch{throw new HumanRealismError('INVALID_INPUT');}if(JSON.stringify(canonical)!==JSON.stringify(r.statePlan))throw new HumanRealismError('INVALID_INPUT');const expectedRisk=evaluateSceneRisk(canonical,r.capabilityMap);if(JSON.stringify(expectedRisk)!==JSON.stringify(r.risk))throw new HumanRealismError('INVALID_INPUT');if(expectedRisk.scenes.some(scene=>scene.status!=='READY'))throw new HumanRealismError('RISK_NOT_READY');let data:unknown;try{data=(await r.intelligence.analyzeStructured<unknown>({instruction:buildHumanRealismInstruction(),inputText:buildHumanRealismInputText(r),media:[],outputSchema:{type:'object',properties:{scenes:{type:'array',minItems:4,maxItems:4,items:{type:'object',properties:Object.fromEntries(keys.map(key=>[key,{type:'string'}])),required:[...keys],additionalProperties:false}}},required:['scenes'],additionalProperties:false},parse:value=>value})).data;}catch(error){if(error instanceof IntelligenceProviderError)throw error;throw new HumanRealismError('PROVIDER_FAILURE');}if(!isDecision(data))throw new HumanRealismError('INVALID_MODEL_OUTPUT');const output:HumanRealism4ScenePlan={schemaVersion:SCHEMA_VERSION,realismVersion:HUMAN_REALISM_VERSION,productId:canonical.productId,sourceEvidenceVersion:canonical.sourceEvidenceVersion,canonicalAssetIds:canonical.canonicalAssetIds,continuity:canonical.continuity,referenceReadiness:canonical.referenceReadiness,referenceLimitations:canonical.referenceLimitations,globalConstraints:HUMAN_REALISM_GLOBAL_CONSTRAINTS,scenes:canonical.scenes.map((scene,index)=>({sceneId:scene.sceneId,index:scene.index,primaryAction:scene.primaryAction,startState:scene.startState,endState:scene.endState,behavior:data.scenes[index]!}))};if(validateHumanRealism4ScenePlan(output,canonical,HUMAN_REALISM_GLOBAL_CONSTRAINTS).length)throw new HumanRealismError('INVALID_MODEL_OUTPUT');return output;}
function isDecision(value:unknown):value is {scenes:HumanRealismBehavior[]}{if(!value||typeof value!=='object')return false;const scenes=(value as Record<string,unknown>).scenes;if(!Array.isArray(scenes)||scenes.length!==4||Object.keys(value as object).length!==1)return false;return scenes.every(scene=>!!scene&&typeof scene==='object'&&Object.keys(scene).length===keys.length&&keys.every(key=>typeof (scene as Record<string,unknown>)[key]==='string'&&((scene as Record<string,unknown>)[key] as string).trim().length>0));}
