import { SCHEMA_VERSION, type ActionId, type CreativeDirectionInput, type DesiredStateEffect, type Global4ScenePlan, type GlobalContinuityState, type R2CommittedProductContext, type TransitionType } from '@mochi/contracts';
import { IntelligenceProviderError, type IntelligenceProvider } from '@mochi/providers';
import { validateGlobalContinuityState } from './continuity.ts'; import { ACTION_SEMANTICS } from './state.ts';
export class PlannerError extends Error { readonly code:'INVALID_INPUT'|'INSUFFICIENT_PLANNABLE_TRUTH'|'INVALID_MODEL_OUTPUT'|'PROVIDER_FAILURE'; constructor(code:'INVALID_INPUT'|'INSUFFICIENT_PLANNABLE_TRUTH'|'INVALID_MODEL_OUTPUT'|'PROVIDER_FAILURE'){super(`PLANNER_ERROR:${code}`);this.code=code;} }
type Role='HOOK'|'FEATURE'|'PROOF'|'CTA';
interface SceneSlotDecision {primaryTruthRefId:string;physicalObjective:string;primaryAction:ActionId;dialogueDraft:string;referenceAssetIds:string[];transitionToNext:TransitionType;}
interface CtaSlotDecision {reuseTruthFromScene:1|2|3;physicalObjective:string;primaryAction:ActionId;dialogueDraft:string;referenceAssetIds:string[];}
interface PlanDecision {productId:string;sourceEvidenceVersion:string;canonicalAssetIds:string[];hook:SceneSlotDecision;feature:SceneSlotDecision;proof:SceneSlotDecision;cta:CtaSlotDecision;}
export interface PlanGlobalScenesRequest {context:R2CommittedProductContext;continuity:GlobalContinuityState;creativeDirection:CreativeDirectionInput;intelligence:IntelligenceProvider;}
const actions=['REACH','PICK_UP','HOLD','MOVE_CLOSER','ROTATE_SLOW','PLACE_DOWN','OPEN_SIMPLE','PRESS_BUTTON','POUR_SIMPLE','APPLY_SIMPLE','POINT']; const effects=['NO_STATE_CHANGE','BECOME_HELD','REMAIN_HELD','BECOME_PLACED','CHANGE_ORIENTATION','CHANGE_PRODUCT_STATE']; const transitions=['CONTINUOUS','MATCH_CUT','JUMP_CUT']; const nonBlank=(v:unknown):v is string=>typeof v==='string'&&v.trim().length>0;
export function buildPlanningTruthCatalog(c:R2CommittedProductContext){const t=c.productTruth;return [{id:'identity',text:t.identityDescription},...t.facts.map(f=>({id:f.factId,text:f.text})),...t.allowedClaims.map(x=>({id:`claim:${x.claimId}`,text:x.text}))];}
export const buildPlannerInstruction=()=> 'GLOBAL PLANNER RULES: Return structured JSON only. Do not author product facts. Use supplied truth IDs only. hook, feature, proof must choose distinct primaryTruthRefId values; cta selects reuseTruthFromScene (1, 2, or 3) only. Choose one allowed primaryAction and usable references per slot. Transitions exist only for hook, feature, proof. Do not author index, role, sceneId, duration, aspect ratio, desired state, startState, or endState.';
export function buildPlannerInputText(r:Pick<PlanGlobalScenesRequest,'context'|'continuity'|'creativeDirection'>){return `GLOBAL_PLAN_INPUT_JSON:\n${JSON.stringify({source:{productId:r.context.productId,sourceEvidenceVersion:r.context.sourceEvidenceVersion,canonicalAssetIds:r.context.canonicalAssetIds},truthCatalog:buildPlanningTruthCatalog(r.context),referenceLimitations:r.context.referenceAssessment.limitationCodes,continuity:r.continuity.immutable,creative:{audience:r.creativeDirection.audience,reviewerPersona:r.creativeDirection.reviewerPersona,tone:r.creativeDirection.tone}})}\nEND_GLOBAL_PLAN_INPUT_JSON.`;}
export async function planGlobal4Scenes(r:PlanGlobalScenesRequest):Promise<Global4ScenePlan>{if(validateGlobalContinuityState(r.continuity,r.context,r.creativeDirection).length)throw new PlannerError('INVALID_INPUT'); const catalog=buildPlanningTruthCatalog(r.context);if(new Set(catalog.map(x=>x.id)).size<3)throw new PlannerError('INSUFFICIENT_PLANNABLE_TRUTH'); const usable=r.context.referenceAssessment.assetAssessments.filter(x=>(x.targetVisibility==='CLEAR'||x.targetVisibility==='PARTIAL')&&(x.identityConfidence==='HIGH'||x.identityConfidence==='MEDIUM')).map(x=>x.assetId);if(!usable.length)throw new PlannerError('INVALID_INPUT');let data:unknown;try{data=(await r.intelligence.analyzeStructured<unknown>({instruction:buildPlannerInstruction(),inputText:buildPlannerInputText(r),media:[],outputSchema:schema(r,catalog.map(x=>x.id),usable),parse:v=>v})).data;}catch(e){if(e instanceof IntelligenceProviderError)throw e;throw new PlannerError('PROVIDER_FAILURE');}if(!isDecision(data,r,catalog.map(x=>x.id),usable))throw new PlannerError('INVALID_MODEL_OUTPUT');const p:Global4ScenePlan={schemaVersion:SCHEMA_VERSION,productId:r.context.productId,sourceEvidenceVersion:r.context.sourceEvidenceVersion,canonicalAssetIds:r.context.canonicalAssetIds,continuity:r.continuity,referenceLimitations:r.context.referenceAssessment.limitationCodes,referenceReadiness:r.context.referenceAssessment.readiness as 'READY'|'LIMITED',scenes:compileDecision(data,r.context.productId)};if(validatePlan(p,r.context,r.continuity,catalog.map(x=>x.id),usable).length)throw new PlannerError('INVALID_MODEL_OUTPUT');return p;}
function schema(r:PlanGlobalScenesRequest,truth:string[],assets:string[]){const base={type:'object',properties:{primaryTruthRefId:{type:'string',enum:truth},physicalObjective:{type:'string'},primaryAction:{type:'string',enum:actions},dialogueDraft:{type:'string'},referenceAssetIds:{type:'array',items:{type:'string',enum:assets},minItems:1},transitionToNext:{type:'string',enum:transitions}},required:['primaryTruthRefId','physicalObjective','primaryAction','dialogueDraft','referenceAssetIds','transitionToNext'],additionalProperties:false};const cta={type:'object',properties:{reuseTruthFromScene:{type:'integer',enum:[1,2,3]},physicalObjective:{type:'string'},primaryAction:{type:'string',enum:actions},dialogueDraft:{type:'string'},referenceAssetIds:{type:'array',items:{type:'string',enum:assets},minItems:1}},required:['reuseTruthFromScene','physicalObjective','primaryAction','dialogueDraft','referenceAssetIds'],additionalProperties:false};return {type:'object',properties:{productId:{type:'string',enum:[r.context.productId]},sourceEvidenceVersion:{type:'string',enum:[r.context.sourceEvidenceVersion]},canonicalAssetIds:{type:'array',enum:[r.context.canonicalAssetIds]},hook:base,feature:base,proof:base,cta},required:['productId','sourceEvidenceVersion','canonicalAssetIds','hook','feature','proof','cta'],additionalProperties:false};}
function compileDecision(data:PlanDecision,productId:string):Global4ScenePlan['scenes']{const slots:[Role,SceneSlotDecision|CtaSlotDecision][]=[['HOOK',data.hook],['FEATURE',data.feature],['PROOF',data.proof],['CTA',data.cta]];const first=slots.slice(0,3) as [Role,SceneSlotDecision][];return slots.map(([role,slot],offset)=>{const index=(offset+1) as 1|2|3|4;const cta=role==='CTA';const primaryTruthRefId=cta?first[(slot as CtaSlotDecision).reuseTruthFromScene-1]![1].primaryTruthRefId:(slot as SceneSlotDecision).primaryTruthRefId;const action=slot.primaryAction;return {sceneId:`${productId}:scene:${index}`,index,role,durationSeconds:8,aspectRatio:'9:16',primaryTruthRefId,physicalObjective:slot.physicalObjective,primaryAction:action,desiredStateEffect:ACTION_SEMANTICS[action].effect as DesiredStateEffect,dialogueDraft:slot.dialogueDraft,referenceAssetIds:slot.referenceAssetIds,...(cta?{}:{transitionToNext:(slot as SceneSlotDecision).transitionToNext})};}) as Global4ScenePlan['scenes'];}
function record(v:unknown):v is Record<string,unknown>{return typeof v==='object'&&v!==null&&!Array.isArray(v);}
function exact(v:Record<string,unknown>,keys:readonly string[]):boolean{return Object.keys(v).length===keys.length&&keys.every(key=>key in v);}
function assets(v:unknown,usable:readonly string[]):v is string[]{return Array.isArray(v)&&v.length>0&&v.every(item=>typeof item==='string'&&usable.includes(item));}
function slot(v:unknown,truth:readonly string[],usable:readonly string[]):v is SceneSlotDecision{return record(v)&&exact(v,['primaryTruthRefId','physicalObjective','primaryAction','dialogueDraft','referenceAssetIds','transitionToNext'])&&typeof v.primaryTruthRefId==='string'&&truth.includes(v.primaryTruthRefId)&&nonBlank(v.physicalObjective)&&typeof v.primaryAction==='string'&&actions.includes(v.primaryAction)&&nonBlank(v.dialogueDraft)&&assets(v.referenceAssetIds,usable)&&typeof v.transitionToNext==='string'&&transitions.includes(v.transitionToNext);}
function ctaSlot(v:unknown,usable:readonly string[]):v is CtaSlotDecision{return record(v)&&exact(v,['reuseTruthFromScene','physicalObjective','primaryAction','dialogueDraft','referenceAssetIds'])&&([1,2,3] as number[]).includes(v.reuseTruthFromScene as number)&&nonBlank(v.physicalObjective)&&typeof v.primaryAction==='string'&&actions.includes(v.primaryAction)&&nonBlank(v.dialogueDraft)&&assets(v.referenceAssetIds,usable);}
function isDecision(v:unknown,r:PlanGlobalScenesRequest,truth:readonly string[],usable:readonly string[]):v is PlanDecision{return record(v)&&exact(v,['productId','sourceEvidenceVersion','canonicalAssetIds','hook','feature','proof','cta'])&&v.productId===r.context.productId&&v.sourceEvidenceVersion===r.context.sourceEvidenceVersion&&Array.isArray(v.canonicalAssetIds)&&JSON.stringify(v.canonicalAssetIds)===JSON.stringify(r.context.canonicalAssetIds)&&slot(v.hook,truth,usable)&&slot(v.feature,truth,usable)&&slot(v.proof,truth,usable)&&ctaSlot(v.cta,usable);}
export function validatePlan(p:Global4ScenePlan,c:R2CommittedProductContext,g:GlobalContinuityState,truth:string[],usable:string[]):string[]{const x:string[]=[];if(p.productId!==c.productId||p.sourceEvidenceVersion!==c.sourceEvidenceVersion||JSON.stringify(p.canonicalAssetIds)!==JSON.stringify(c.canonicalAssetIds))x.push('source');if(!sameContinuity(p.continuity,g))x.push('continuity');if(JSON.stringify(p.referenceLimitations)!==JSON.stringify(c.referenceAssessment.limitationCodes))x.push('limitations');if(p.referenceReadiness!==c.referenceAssessment.readiness)x.push('readiness');if(p.scenes.length!==4)x.push('count');const roles=['HOOK','FEATURE','PROOF','CTA'];const ids=new Set<string>(),prim=new Set<string>();p.scenes.forEach((s,i)=>{if(s.index!==i+1||s.role!==roles[i])x.push('sequence');if(ids.has(s.sceneId)||s.sceneId!==p.productId+':scene:'+s.index)x.push('scene_id');ids.add(s.sceneId);if(s.durationSeconds!==8||s.aspectRatio!=='9:16')x.push('format');if(!truth.includes(s.primaryTruthRefId))x.push('truth');if(i<3&&prim.has(s.primaryTruthRefId))x.push('duplicate_truth');if(i<3)prim.add(s.primaryTruthRefId);if(i===3&&!prim.has(s.primaryTruthRefId))x.push('cta_truth');if(!actions.includes(s.primaryAction)||!effects.includes(s.desiredStateEffect)||!nonBlank(s.physicalObjective)||!nonBlank(s.dialogueDraft))x.push('scene_fields');if(actions.includes(s.primaryAction)&&ACTION_SEMANTICS[s.primaryAction as ActionId].effect!==s.desiredStateEffect)x.push('action_effect');if(!s.referenceAssetIds.length||s.referenceAssetIds.some(a=>!usable.includes(a)))x.push('assets');if((i<3&&!s.transitionToNext)||(i===3&&s.transitionToNext!==undefined)||(s.transitionToNext!==undefined&&!transitions.includes(s.transitionToNext)))x.push('transition');if(('startState'in s)||('endState'in s))x.push('state_leak');});return x;}
function sameContinuity(a:Global4ScenePlan['continuity'],b:Global4ScenePlan['continuity']):boolean{return a.schemaVersion===b.schemaVersion&&a.productId===b.productId&&a.sourceEvidenceVersion===b.sourceEvidenceVersion&&a.canonicalAssetIds.length===b.canonicalAssetIds.length&&a.canonicalAssetIds.every((id,i)=>id===b.canonicalAssetIds[i])&&a.immutable.handIdentity.skinTone===b.immutable.handIdentity.skinTone&&a.immutable.handIdentity.nailStyle===b.immutable.handIdentity.nailStyle&&a.immutable.handIdentity.jewelry===b.immutable.handIdentity.jewelry&&a.immutable.handIdentity.dominantHand===b.immutable.handIdentity.dominantHand&&a.immutable.environment.location===b.immutable.environment.location&&a.immutable.environment.surface===b.immutable.environment.surface&&a.immutable.environment.background===b.immutable.environment.background&&a.immutable.environment.lighting===b.immutable.environment.lighting&&a.immutable.cameraFamily===b.immutable.cameraFamily&&a.immutable.voiceIdentity.voiceGender===b.immutable.voiceIdentity.voiceGender&&a.immutable.voiceIdentity.voiceRegion===b.immutable.voiceIdentity.voiceRegion&&a.immutable.voiceIdentity.voiceStyle===b.immutable.voiceIdentity.voiceStyle;}
