import { compileSceneAnchorsV1, validateProductionSnapshotV1, validateSceneAnchorAgainstSnapshot, type ProductionSnapshotV1, type SceneAnchorV1 } from '@mochi/contracts';
import { compileFlowProductionRequestV1, mapFlowGeneratedCandidateV1, type FlowProductionDriverV1, type FlowReferenceBindingV1 } from './flow-production.ts';
import { evaluateSceneQcV1, SceneQcError, type PresentationDynamicsV1, type SceneQcReferenceMediaV1, type SceneQcReportV1, type SceneQcVideoMediaV1 } from './scene-qc.ts';
import type { IntelligenceProvider, StructuredIntelligenceRequest } from './intelligence.ts';

export const FOUR_SCENE_PRODUCTION_V1 = 'FOUR_SCENE_PRODUCTION_V1' as const;
export type PairwiseGate = 'PRODUCT_IDENTITY_CONTINUITY'|'HAND_IDENTITY_CONTINUITY'|'ENVIRONMENT_CONTINUITY'|'LIGHTING_CONTINUITY'|'VISIBLE_STATE_HANDOFF'|'NO_UNEXPLAINED_IDENTITY_RESET';
export type GlobalGate = 'PRODUCT_CONSISTENCY'|'HAND_CONSISTENCY'|'ENVIRONMENT_LIGHTING_CONSISTENCY'|'SPEAKER_CONSISTENCY'|'SEQUENCE_COHERENCE'|'NARRATIVE_ROLE_COHERENCE';
export interface SequenceGate<T extends string> { readonly gate:T; readonly status:'PASS'|'FAIL'; }
export interface PairwiseAssessmentV1 { readonly fromSceneId:string; readonly toSceneId:string; readonly gates:readonly SequenceGate<PairwiseGate>[]; }
export interface SequenceResultV1 { readonly version:typeof FOUR_SCENE_PRODUCTION_V1; readonly status:'FOUR_SCENE_SEQUENCE_PASS'|'SCENE_QC_FAILED'|'SEQUENCE_QC_FAILED'; readonly failedSceneId?:string; readonly sceneQcReports:readonly SceneQcReportV1[]; readonly pairwiseAssessments:readonly PairwiseAssessmentV1[]; readonly globalGates:readonly SequenceGate<GlobalGate>[]; readonly visualVariation:PresentationDynamicsV1|undefined; readonly failureReasons:readonly string[]; readonly sceneIntelligenceCallCount:number; readonly sequenceIntelligenceCallCount:0|1; readonly totalIntelligenceCallCount:number; }
export interface GeneratedVideoMediaResolverV1 { resolve(candidateAssetId:string, sceneId:string):Promise<SceneQcVideoMediaV1>; }
export interface FourSceneProductionInputV1 { readonly snapshot:ProductionSnapshotV1; readonly anchors:readonly [SceneAnchorV1,SceneAnchorV1,SceneAnchorV1,SceneAnchorV1]; readonly referenceBindings:readonly [readonly FlowReferenceBindingV1[],readonly FlowReferenceBindingV1[],readonly FlowReferenceBindingV1[],readonly FlowReferenceBindingV1[]]; readonly referenceMedia:readonly [readonly SceneQcReferenceMediaV1[],readonly SceneQcReferenceMediaV1[],readonly SceneQcReferenceMediaV1[],readonly SceneQcReferenceMediaV1[]]; readonly driver:FlowProductionDriverV1; readonly videoMediaResolver:GeneratedVideoMediaResolverV1; readonly intelligence: IntelligenceProvider; }
export class SequenceQcError extends Error { readonly code:'INVALID_INPUT'|'INVALID_MODEL_OUTPUT'|'PROVIDER_FAILURE'; constructor(code:SequenceQcError['code']) { super(`SEQUENCE_QC_ERROR:${code}`);this.code=code;this.name='SequenceQcError'; } }
const pairs=['PRODUCT_IDENTITY_CONTINUITY','HAND_IDENTITY_CONTINUITY','ENVIRONMENT_CONTINUITY','LIGHTING_CONTINUITY','VISIBLE_STATE_HANDOFF','NO_UNEXPLAINED_IDENTITY_RESET'] as const;
const globals=['PRODUCT_CONSISTENCY','HAND_CONSISTENCY','ENVIRONMENT_LIGHTING_CONSISTENCY','SPEAKER_CONSISTENCY','SEQUENCE_COHERENCE','NARRATIVE_ROLE_COHERENCE'] as const;
const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b); const exact=(v:unknown,k:readonly string[])=>!!v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).length===k.length&&k.every(x=>x in (v as object));
const gateOutputSchema=(values:readonly string[],count:number)=>({type:'array',minItems:count,maxItems:count,items:{type:'object',additionalProperties:false,required:['gate','status'],properties:{gate:{type:'string',enum:values},status:{type:'string',enum:['PASS','FAIL']}}}});
/** Complete closed first trust-boundary schema. parse remains the second boundary. */
export const SEQUENCE_QC_OUTPUT_SCHEMA={type:'object',additionalProperties:false,required:['pairs','global','visualVariation'],properties:{pairs:{type:'array',minItems:3,maxItems:3,items:{type:'object',additionalProperties:false,required:['fromSceneId','toSceneId','gates'],properties:{fromSceneId:{type:'string'},toSceneId:{type:'string'},gates:gateOutputSchema(pairs,6)}}},global:gateOutputSchema(globals,6),visualVariation:{type:'object',additionalProperties:false,required:['status','meaningfulVisualProgression','excessiveStaticHold','rhythmIntentObserved','notes'],properties:{status:{type:'string',enum:['PASS','WARN']},meaningfulVisualProgression:{type:'boolean'},excessiveStaticHold:{type:'boolean'},rhythmIntentObserved:{type:'boolean'},notes:{type:'string'}}}}} as const;
function precheck(input:FourSceneProductionInputV1):void { const {snapshot,anchors}=input; if(validateProductionSnapshotV1(snapshot).length||anchors.length!==4) throw new SequenceQcError('INVALID_INPUT'); const expected=compileSceneAnchorsV1(snapshot); for(let i=0;i<4;i++){const a=anchors[i]!; if(validateSceneAnchorAgainstSnapshot(a,snapshot).length||a.index!==i+1||a.role!==(['HOOK','FEATURE','PROOF','CTA'] as const)[i]||!same(a,expected[i])) throw new SequenceQcError('INVALID_INPUT'); if(i&&(!same(anchors[i-1]!.endState,a.startState)||!same(anchors[0]!.hardContinuity,a.hardContinuity))) throw new SequenceQcError('INVALID_INPUT');} }
function gates(value:unknown, names:readonly string[]):readonly SequenceGate<string>[]|undefined { if(!Array.isArray(value)||value.length!==names.length||!value.every(x=>exact(x,['gate','status'])&&names.includes((x as {gate:string}).gate)&&['PASS','FAIL'].includes((x as {status:string}).status))||new Set(value.map(x=>(x as {gate:string}).gate)).size!==names.length)return;return value as readonly SequenceGate<string>[]; }
type Observation={pairs:readonly PairwiseAssessmentV1[];global:readonly SequenceGate<GlobalGate>[];visualVariation:PresentationDynamicsV1;};
function parse(value:unknown):Observation { if(!exact(value,['pairs','global','visualVariation']))throw new SequenceQcError('INVALID_MODEL_OUTPUT');const r=value as Record<string,unknown>;if(!Array.isArray(r.pairs)||r.pairs.length!==3||!r.pairs.every((p,i)=>exact(p,['fromSceneId','toSceneId','gates'])&&typeof (p as {fromSceneId:unknown}).fromSceneId==='string'&&typeof (p as {toSceneId:unknown}).toSceneId==='string'&&!!gates((p as {gates:unknown}).gates,pairs)))throw new SequenceQcError('INVALID_MODEL_OUTPUT');const g=gates(r.global,globals);const d=r.visualVariation as Record<string,unknown>;if(!g||!exact(d,['status','meaningfulVisualProgression','excessiveStaticHold','rhythmIntentObserved','notes'])||!['PASS','WARN'].includes(d.status as string)||typeof d.meaningfulVisualProgression!=='boolean'||typeof d.excessiveStaticHold!=='boolean'||typeof d.rhythmIntentObserved!=='boolean'||typeof d.notes!=='string')throw new SequenceQcError('INVALID_MODEL_OUTPUT');return {pairs:r.pairs as readonly PairwiseAssessmentV1[],global:g as readonly SequenceGate<GlobalGate>[],visualVariation:d as unknown as PresentationDynamicsV1}; }
function sequenceRequest(input:Pick<FourSceneProductionInputV1,'anchors'|'referenceMedia'>,reports:readonly SceneQcReportV1[],videos:readonly SceneQcVideoMediaV1[]):StructuredIntelligenceRequest<Observation>{const a=input.anchors;return {instruction:'SEQUENCE_QC_V1: assess all supplied videos together for each exact pairwise and global continuity gate. Same perceived speaker/timbre is critical; performance/prosody may vary by role. Soft framing variation is allowed. Return only declared JSON.',inputText:JSON.stringify({roles:a.map(x=>x.role),stateHandoffs:a.slice(0,3).map((x,i)=>({from:x.sceneId,to:a[i+1]!.sceneId,end:x.endState,start:a[i+1]!.startState})),hardContinuity:a[0]!.hardContinuity,voice:a[0]!.voiceIdentityId,reports:reports.map(x=>({sceneId:x.sceneId,candidateAssetId:x.candidateAssetId}))}),media:[...videos.map(x=>({assetId:x.candidateAssetId,mimeType:x.mimeType,dataBase64:x.dataBase64})),...input.referenceMedia[0]!.map(x=>({assetId:x.assetId,mimeType:x.mimeType,dataBase64:x.dataBase64}))],outputSchema:SEQUENCE_QC_OUTPUT_SCHEMA,parse};}
export interface ManualCandidateSequenceQcInputV1 { readonly snapshot:ProductionSnapshotV1; readonly anchors:readonly [SceneAnchorV1,SceneAnchorV1,SceneAnchorV1,SceneAnchorV1]; readonly referenceMedia:FourSceneProductionInputV1['referenceMedia']; readonly sceneQcReports:readonly [SceneQcReportV1,SceneQcReportV1,SceneQcReportV1,SceneQcReportV1]; readonly videos:readonly [SceneQcVideoMediaV1,SceneQcVideoMediaV1,SceneQcVideoMediaV1,SceneQcVideoMediaV1]; readonly intelligence:IntelligenceProvider; }
/** Continuity entry point for four externally generated, individually passed candidates. */
export async function runManualCandidateSequenceQcV1(input:ManualCandidateSequenceQcInputV1):Promise<Pick<SequenceResultV1,'status'|'pairwiseAssessments'|'globalGates'|'visualVariation'|'failureReasons'|'sequenceIntelligenceCallCount'>> { precheck({snapshot:input.snapshot,anchors:input.anchors} as FourSceneProductionInputV1); if(input.sceneQcReports.some((report,index)=>report.result!=='SCENE_QC_PASS'||report.sceneId!==input.anchors[index]!.sceneId||report.candidateAssetId!==input.videos[index]!.candidateAssetId)) throw new SequenceQcError('INVALID_INPUT'); let observation:Observation; try { observation=(await input.intelligence.analyzeStructured(sequenceRequest(input,input.sceneQcReports,input.videos))).data; observation=parse(observation); } catch(error) { if(error instanceof SequenceQcError) throw error; throw new SequenceQcError('PROVIDER_FAILURE'); } const ordered=<T extends string>(items:readonly SequenceGate<T>[],names:readonly T[])=>names.map(gate=>items.find(item=>item.gate===gate)!); const pairwise=observation.pairs.map(pair=>({fromSceneId:pair.fromSceneId,toSceneId:pair.toSceneId,gates:ordered(pair.gates as readonly SequenceGate<PairwiseGate>[],pairs)})); if(!pairwise.every((pair,index)=>pair.fromSceneId===input.anchors[index]!.sceneId&&pair.toSceneId===input.anchors[index+1]!.sceneId)) throw new SequenceQcError('INVALID_MODEL_OUTPUT'); const globalGates=ordered(observation.global,globals); const failureReasons=[...pairwise.flatMap(pair=>pair.gates.filter(gate=>gate.status==='FAIL').map(gate=>gate.gate)),...globalGates.filter(gate=>gate.status==='FAIL').map(gate=>gate.gate)]; return {status:failureReasons.length?'SEQUENCE_QC_FAILED':'FOUR_SCENE_SEQUENCE_PASS',pairwiseAssessments:pairwise,globalGates,visualVariation:observation.visualVariation,failureReasons,sequenceIntelligenceCallCount:1}; }
export async function runFourSceneProductionV1(input:FourSceneProductionInputV1):Promise<SequenceResultV1>{precheck(input);const reports:SceneQcReportV1[]=[];const videos:SceneQcVideoMediaV1[]=[];for(let i=0;i<4;i++){const anchor=input.anchors[i]!,request=compileFlowProductionRequestV1(anchor,input.referenceBindings[i]!);const raw=await input.driver.generateScene(request);const candidate=mapFlowGeneratedCandidateV1(raw,request);const video=await input.videoMediaResolver.resolve(candidate.candidateAssetId,candidate.sceneId);videos.push(video);let report:SceneQcReportV1;try{report=await evaluateSceneQcV1({candidate,anchor,productionRequest:request,video,references:input.referenceMedia[i]!,intelligence:input.intelligence});}catch(error){if(error instanceof SceneQcError)throw error;throw error;}reports.push(report);if(report.result==='SCENE_QC_FAIL')return {version:FOUR_SCENE_PRODUCTION_V1,status:'SCENE_QC_FAILED',failedSceneId:anchor.sceneId,sceneQcReports:reports,pairwiseAssessments:[],globalGates:[],visualVariation:undefined,failureReasons:report.criticalFailureReasons,sceneIntelligenceCallCount:reports.length,sequenceIntelligenceCallCount:0,totalIntelligenceCallCount:reports.length};}
let o:Observation;try{o=(await input.intelligence.analyzeStructured(sequenceRequest(input,reports,videos))).data;o=parse(o);}catch(error){if(error instanceof SequenceQcError)throw error;throw new SequenceQcError('PROVIDER_FAILURE');}const ordered=<T extends string>(items:readonly SequenceGate<T>[],names:readonly T[])=>names.map(g=>items.find(x=>x.gate===g)!);const pairwise=o.pairs.map((p,i)=>({fromSceneId:p.fromSceneId,toSceneId:p.toSceneId,gates:ordered(p.gates as readonly SequenceGate<PairwiseGate>[],pairs)}));if(!pairwise.every((p,i)=>p.fromSceneId===input.anchors[i]!.sceneId&&p.toSceneId===input.anchors[i+1]!.sceneId))throw new SequenceQcError('INVALID_MODEL_OUTPUT');const global=ordered(o.global,globals);const failures=[...pairwise.flatMap(p=>p.gates.filter(g=>g.status==='FAIL').map(g=>g.gate)),...global.filter(g=>g.status==='FAIL').map(g=>g.gate)];return {version:FOUR_SCENE_PRODUCTION_V1,status:failures.length?'SEQUENCE_QC_FAILED':'FOUR_SCENE_SEQUENCE_PASS',sceneQcReports:reports,pairwiseAssessments:pairwise,globalGates:global,visualVariation:o.visualVariation,failureReasons:failures,sceneIntelligenceCallCount:4,sequenceIntelligenceCallCount:1,totalIntelligenceCallCount:5};}
