import { isCanonicalV1ReviewVoiceKey } from '@mochi/core';
import type { VoiceGender, VoiceIdentityId, VoiceRegion } from '@mochi/contracts';import { VoiceProviderError, type VoiceProvider, type VoiceSynthesisRequest, type VoiceSynthesisResult, validateVoiceSynthesisRequest } from './voice.ts';
export interface SaydiVoiceBinding { readonly voiceIdentityId:VoiceIdentityId; readonly providerVoiceId:string; readonly providerVoiceName:string; readonly language:'vi-VN'; readonly voiceGender:VoiceGender; readonly voiceRegion:VoiceRegion; readonly voiceStyle:string; readonly synthesisSettings:Readonly<Record<string,string|number|boolean>>; }
export interface SaydiBrowserDriverResult { readonly audioFormat:'WAV'; readonly measuredDurationMs:number; readonly sha256:string; readonly runtimeArtifactRef:string; }
export interface SaydiBrowserDriver { synthesize(binding:SaydiVoiceBinding,text:string):Promise<SaydiBrowserDriverResult>; }
export class SaydiBrowserVoiceProvider implements VoiceProvider { readonly id='saydi-browser-voice'; readonly #bindings:ReadonlyMap<string,SaydiVoiceBinding>; private readonly driver:SaydiBrowserDriver;constructor(bindings:readonly SaydiVoiceBinding[],driver:SaydiBrowserDriver){this.driver=driver;this.#bindings=createSaydiVoiceBindingRegistry(bindings);}async synthesize(request:VoiceSynthesisRequest):Promise<VoiceSynthesisResult>{validateVoiceSynthesisRequest(request);const binding=this.#bindings.get(request.voiceIdentityId);if(!binding)throw new VoiceProviderError('VOICE_BINDING_MISSING');if(!sameBindingRequest(binding,request))throw new VoiceProviderError('VOICE_BINDING_MISMATCH');let result:SaydiBrowserDriverResult;try{result=await this.driver.synthesize(binding,request.text);}catch{throw new VoiceProviderError('SYNTHESIS_FAILED');}if(!result||result.audioFormat!=='WAV'||!Number.isFinite(result.measuredDurationMs)||result.measuredDurationMs<=0||!isSha256(result.sha256)||!result.runtimeArtifactRef.trim())throw new VoiceProviderError('INVALID_AUDIO_RESULT');return{voiceIdentityId:request.voiceIdentityId,audioFormat:'WAV',measuredDurationMs:result.measuredDurationMs,sha256:result.sha256,runtimeArtifactRef:result.runtimeArtifactRef};}}
export function createSaydiVoiceBindingRegistry(bindings:readonly SaydiVoiceBinding[]):ReadonlyMap<string,SaydiVoiceBinding>{const result=new Map<string,SaydiVoiceBinding>();for(const binding of bindings){if(!isCanonicalV1ReviewVoiceKey(binding)||!binding.providerVoiceId.trim()||!binding.providerVoiceName.trim()||binding.language!=='vi-VN'||(binding.voiceGender!=='MALE'&&binding.voiceGender!=='FEMALE')||(binding.voiceRegion!=='SOUTH'&&binding.voiceRegion!=='NORTH')||!binding.voiceStyle.trim()||!binding.synthesisSettings||Object.values(binding.synthesisSettings).some(v=>typeof v!=='string'&&typeof v!=='number'&&typeof v!=='boolean'))throw new VoiceProviderError('VOICE_IDENTITY_UNSUPPORTED');if(result.has(binding.voiceIdentityId))throw new VoiceProviderError('VOICE_IDENTITY_UNSUPPORTED');result.set(binding.voiceIdentityId,Object.freeze({...binding,synthesisSettings:Object.freeze({...binding.synthesisSettings})}));}return result;}
function isSha256(value:string):boolean{return /^[a-f0-9]{64}$/iu.test(value);}
function sameBindingRequest(binding:SaydiVoiceBinding,request:VoiceSynthesisRequest):boolean{return binding.language===request.language&&binding.voiceGender===request.voiceGender&&binding.voiceRegion===request.voiceRegion&&binding.voiceStyle===request.voiceStyle;}
